{{- if (include "sonatypeiq-mcp.useGCPSecret" .) }}
{{- if .Values.secret.gcp.credentialsFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonatypeiq-mcp.fullname" . }}-gcp-sa
  labels:
    {{- include "sonatypeiq-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: {{ .Values.secret.gcp.credentialsFile | b64enc | quote }}
{{- end }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sonatypeiq-mcp.fullname" . }}-spc
  labels:
    {{- include "sonatypeiq-mcp.labels" . | nindent 4 }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ required "secret.gcp.projectId is required when provider is gcp" .Values.secret.gcp.projectId }}/secrets/{{ required "secret.gcp.secretId is required when provider is gcp" .Values.secret.gcp.secretId }}/versions/latest"
        fileName: "oidc_client_secret"
        key: "oidc_client_secret"
      - resourceName: "projects/{{ .Values.secret.gcp.projectId }}/secrets/{{ .Values.secret.gcp.secretId }}/versions/latest"
        fileName: "web_token"
        key: "web_token"
      - resourceName: "projects/{{ .Values.secret.gcp.projectId }}/secrets/{{ .Values.secret.gcp.secretId }}/versions/latest"
        fileName: "cookie_token"
        key: "cookie_token"
{{- if .Values.secret.gcp.credentialsFile }}
  secretObjects:
    - secretName: {{ include "sonatypeiq-mcp.fullname" . }}-gcp-secret
      type: Opaque
      data:
        - objectName: "oidc_client_secret"
          key: "oidc_client_secret"
        - objectName: "web_token"
          key: "web_token"
        - objectName: "cookie_token"
          key: "cookie_token"
{{- end }}
{{- end }}
