{{- if (include "sonatypeiq-mcp.useStaticSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonatypeiq-mcp.fullname" . }}-secret
  labels:
    {{- include "sonatypeiq-mcp.labels" . | nindent 4 }}
  {{- with .Values.secret.static.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  oidc_client_secret: {{ .Values.secret.static.oidcClientSecret | quote }}
  bearer_token: {{ .Values.secret.static.bearerToken | quote }}
  cookie_token: {{ .Values.secret.static.cookieToken | quote }}
  ldap_bind_password: {{ .Values.secret.static.ldapBindPassword | quote }}
{{- end }}
