// Code generated by https://github.com/flowgent-labs/mcpfather

package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"net/http"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/mark3labs/mcp-go/server"
	mcputils "sonatypeiq-mcp/pkg/helpers"
	mcpcli "sonatypeiq-mcp/pkg/mcpcli"
	mcpserver "sonatypeiq-mcp/pkg/mcpserver"
)

// logHTTP wraps any handler and logs incoming HTTP requests + responses
// with kubectl-style progressive verbosity:
//
//	v >= 1:  access log — method, URI, status, duration
//	v >= 4:  + request header names
//	v >= 8:  + full request header values (Authorization/Cookie redacted) + body length
//	v >= 10: + request body content (first 2048 bytes)
func logHTTP(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		v := mcputils.GetVerbosity()

		// Extract session ID for logging and pass it downstream via context
		sessionID := r.Header.Get("Mcp-Session-Id")
		ctx := mcputils.WithSessionID(r.Context(), sessionID)
		r = r.WithContext(ctx)

		sid := sessionID
		if sid == "" {
			sid = "-"
		}

		// Log request progressively
		if v >= 4 {
			reqLog := fmt.Sprintf("%s [http] sid=%s --> %s %s", start.Format(time.RFC3339), sid, r.Method, r.URL.RequestURI())
			reqLog += fmt.Sprintf(" headers=%s", mcputils.HTTPHeaderNames(r.Header))
			fmt.Fprintln(os.Stderr, reqLog)
		}
		if v >= 8 {
			for key, values := range r.Header {
				for _, val := range values {
					display := val
					if mcputils.IsSensitiveHeader(key) {
						display = "***"
					}
					fmt.Fprintf(os.Stderr, "%s [http] sid=%s    req %s: %s\n", start.Format(time.RFC3339), sid, key, display)
				}
			}
		}
		// v>=8: body length; v>=10: body content
		if v >= 8 && r.Body != nil && r.ContentLength > 0 {
			fmt.Fprintf(os.Stderr, "%s [http] sid=%s    req body: %d bytes\n", start.Format(time.RFC3339), sid, r.ContentLength)
		}
		if v >= 10 && r.Body != nil {
			bodyBytes, _ := io.ReadAll(r.Body)
			r.Body = io.NopCloser(strings.NewReader(string(bodyBytes)))
			fmt.Fprintf(os.Stderr, "%s [http] sid=%s    req body (%d bytes): %s\n", start.Format(time.RFC3339), sid, len(bodyBytes), truncate(string(bodyBytes), 2048))
		}

		lw := &loggingWriter{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(lw, r)

		// Log response
		if v >= 1 {
			fmt.Fprintf(os.Stderr, "%s [http] sid=%s <-- %d %s %s (%s)\n", time.Now().Format(time.RFC3339), sid, lw.status, r.Method, r.URL.RequestURI(), time.Since(start).Round(time.Millisecond))
		}
	})
}

type loggingWriter struct {
	http.ResponseWriter
	status int
}

func (l *loggingWriter) WriteHeader(code int) {
	l.status = code
	l.ResponseWriter.WriteHeader(code)
}

// Flush implements http.Flusher by delegating to the underlying ResponseWriter.
func (l *loggingWriter) Flush() {
	if f, ok := l.ResponseWriter.(http.Flusher); ok {
		f.Flush()
	}
}

func truncate(s string, max int) string {
	if len(s) > max {
		return s[:max] + "..."
	}
	if s == "" {
		return "(empty)"
	}
	return s
}

func usage() {
	fmt.Fprintf(os.Stderr, `sonatypeiq-mcp — Enterprise-grade MCP server generated by MCPfather (https://github.com/flowgent-labs/mcpfather).

Usage: sonatypeiq-mcp [OPTIONS] [TOOL_NAME] [JSON_ARGS]

Options:
  -t, --transport <stdio|http|cli>  Transport mode (default "stdio")
                                     cli mode: invoke a tool directly from the command line
  -p, --port <number>                HTTP server port (default 8080)
  --metrics-port <number>           Override mgmt.port from config.yaml (0: use config)
  -v, --verbose <0-10>              Request logging verbosity (kubectl-style progressive)
                                      0=silent, 1-3=status+duration, 4-7=+headers(names),
                                      8-9=+headers(values)+body(len), 10=+body(content)
  --print-default-config             Print default config.yaml to stdout and exit
  -h, --help                        Show this help message

CLI Mode:
  sonatypeiq-mcp -t cli list                   List all available tools
  sonatypeiq-mcp -t cli <tool-name> [OPTIONS]   Invoke a tool with GNU-style options
                                                   Use --help for tool-specific help
`)
}

func printDefaultConfigYAML() {
	fmt.Println("# sonatypeiq-mcp MCP server configuration — generated by mcpfather (https://github.com/flowgent-labs/mcpfather)")
	fmt.Println("# Place this file at: $HOME/." + "sonatypeiq-mcp" + "/config.yaml")
	fmt.Println("# Environment variables with MCP__ prefix override these values.")
	fmt.Println("# e.g. MCP__AUTH__BACKEND__OIDC__CLIENT_ID overrides auth.backend.oidc.client_id")
	fmt.Println()
	fmt.Println("# ---- Upstream API endpoint ----")
	fmt.Println("upstream:")
	fmt.Println("  endpoint: \"\"               # upstream API base URL (e.g. https://api.example.com)")
	fmt.Println("  # When true, the MCP session ID is forwarded as X-MCP-Session-ID header.")
	fmt.Println("  enable_mcp_session_forward: true")
	fmt.Println()
	fmt.Println("# ---- Runtime settings ----")
	fmt.Println("runtime:")
	fmt.Println("  download_dir: \"\"             # override download directory for binary responses")
	fmt.Println("  log_authorization: false     # set true to print Authorization header values in logs")
	fmt.Println()
	fmt.Println("# ---- Management Endpoints (metrics, tracing, pprof) ----")
	fmt.Println("mgmt:")
	fmt.Println("  enabled: true")
	fmt.Println("  host: 0.0.0.0")
	fmt.Println("  port: 9991")
	fmt.Println("  pprof:")
	fmt.Println("    enabled: false")
	fmt.Println("    server_bind: 0.0.0.0:6669")
	fmt.Println("  otel:")
	fmt.Println("    enabled: false")
	fmt.Println("    endpoint: localhost:4317")
	fmt.Println("    protocol: grpc             # grpc | http/protobuf | http/json")
	fmt.Println("    timeout: 10000             # connection timeout in milliseconds")
	fmt.Println("    sample_rate: 1.0           # 0.0–1.0 trace sampling ratio")
	fmt.Println("  metrics:")
	fmt.Println("    enabled: true")
	fmt.Println("    prometheus: true")
	fmt.Println("    export_interval: 30s")
	fmt.Println("    histogram_boundaries:")
	fmt.Println("      task: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120]")
	fmt.Println("    labels: {}                 # static labels added to every metric")
	fmt.Println()
	fmt.Println("# ---- Authentication ----")
	fmt.Println("# frontend = inbound: validates bearer tokens presented by MCP clients (AI agents).")
	fmt.Println("# backend  = outbound: credentials the server uses to call upstream APIs.")
	fmt.Println("# The two are independent — the inbound token is never reused outbound")
	fmt.Println("# (see MCP Authorization spec: Token Passthrough Prohibition).")
	fmt.Println("auth:")
	fmt.Println("  frontend:")
	fmt.Println("    # Standard OAuth 2.1 / OIDC JWT bearer validation (Resource Server role, RFC 9728).")
	fmt.Println("    # Only enforced on the http transport; stdio has no network boundary.")
	fmt.Println("    oidc:")
	fmt.Println("      enabled: false")
	fmt.Println("      issuer: \"\"            # e.g. https://idp.example.com/realms/myrealm")
	fmt.Println("      jwks_uri: \"\"          # optional override (auto-discovered from issuer if empty)")
	fmt.Println("      audience: \"\"          # expected JWT \"aud\" claim; also published as the RFC 9728 protected-resource identifier")
	fmt.Println("      # When true, validated frontend JWT claims (sub, email) are forwarded upstream")
	fmt.Println("      # as X-MCP-Client-Token-Sub and X-MCP-Client-Token-Email headers.")
	fmt.Println("      enable_client_token_claim_forward: true")
	fmt.Println("      # Additional JWT claims to forward as X-MCP-Client-Token-<Header-Name> headers.")
	fmt.Println("      # e.g. [\"given_name\", \"family_name\", \"preferred_username\"]")
	fmt.Println("      # additional_client_token_claim_forward: []")
	fmt.Println()
	fmt.Println("  backend:")
	fmt.Println("    # OIDC client credentials flow (machine-to-machine)")
	fmt.Println("    oidc:")
	fmt.Println("      enabled: false")
	fmt.Println("      issuer: \"\"            # e.g. https://keycloak.example.com/realms/myrealm")
	fmt.Println("      client_id: \"\"")
	fmt.Println("      client_secret: \"\"")
	fmt.Println("      scopes: \"openid\"       # space-separated scope list")
	fmt.Println("      token_url: \"\"          # optional override (auto-discovered from issuer if empty)")
	fmt.Println()
	fmt.Println("    # Static credentials for legacy / simple APIs")
	fmt.Println("    static:")
	fmt.Println("      bearer_token: \"\"       # static Bearer token")
	fmt.Println("      bearer_token_file: \"\"   # path to file containing bearer token (K8s secrets)")
	fmt.Println("      cookie_token: \"\"        # static cookie (e.g. JSESSIONID for legacy systems)")
	fmt.Println("      cookie_token_file: \"\"   # path to file containing cookie token (K8s secrets)")
	fmt.Println()
	fmt.Println("# ---- Native MCP Tools ----")
	fmt.Println("nativeTools:")
	fmt.Println("  expose:")
	fmt.Println("    register_all_tools_by_default: false")
	fmt.Println("    includes: []")
	fmt.Println("    excludes: []")
	fmt.Println()
	fmt.Println("# ---- Virtual Tools ----")
	fmt.Println("# Compose multiple native tools into a single virtual tool via a declarative")
	fmt.Println("# pipeline (call -> jq -> foreach -> emit -> return).")
	fmt.Println("# Schema: https://github.com/flowgent-labs/mcpfather/blob/main/.agents/skills/virtual-tool-creator/resources/dsl-schema.json")
	fmt.Println("#")
	fmt.Println("# Real Enterprise Virtual Tools definitions:")
	fmt.Println("#   - sonarqube-example-config.yaml")
	fmt.Println("#     https://github.com/flowgent-labs/mcpfather/blob/main/.agents/skills/virtual-tool-creator/resources/sonarqube-example-config.yaml")
	fmt.Println("#   - sonatypeiq-example-config.yaml")
	fmt.Println("#     https://github.com/flowgent-labs/mcpfather/blob/main/.agents/skills/virtual-tool-creator/resources/sonatypeiq-example-config.yaml")
	fmt.Println("virtualTools: []")
}

func main() {
	flag.CommandLine.SetOutput(os.Stderr)
	flag.Usage = usage

	transport := flag.String("t", "stdio", "Transport mode: stdio, http, or cli")
	flag.StringVar(transport, "transport", "stdio", "Transport mode: stdio, http, or cli")
	port := flag.Int("p", 8080, "HTTP server port (only used when transport=http)")
	flag.IntVar(port, "port", 8080, "HTTP server port (only used when transport=http)")
	metricsPort := flag.Int("metrics-port", 0, "Override mgmt.port from config.yaml (0: use config)")
	verbose := flag.Int("v", 0, "Request logging verbosity level (0-10)")
	flag.IntVar(verbose, "verbose", 0, "Request logging verbosity level (0-10)")
	printDefaultConfig := flag.Bool("print-default-config", false, "Print default config.yaml to stdout and exit")
	flag.Parse()

	if *printDefaultConfig {
		printDefaultConfigYAML()
		return
	}

	// Load config from $HOME/.{binaryName}/config.yaml with MCP__ env overrides
	cfg, err := mcputils.LoadConfig("sonatypeiq-mcp")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: config load failed: %v\n", err)
	}
	if cfg == nil {
		cfg = &mcputils.Config{}
	}
	mcputils.SetConfig(cfg)

	// Initialize backend (outbound) credential managers (no-op if disabled)
	mcputils.InitOIDC(cfg.Auth.Backend.OIDC)
	defer mcputils.ShutdownOIDC()

	mcputils.SetVerbosity(*verbose)

	upstreamEndpoint := mcputils.GetUpstreamEndpoint()
	isDefault := mcputils.IsDefaultUpstreamEndpoint()

	fmt.Fprintf(os.Stderr, "Upstream endpoint: %s\n", upstreamEndpoint)
	if isDefault {
		fmt.Fprintln(os.Stderr, "Warning: upstream endpoint not configured. Using default (httpbin.org/anything) which echoes requests. Set upstream.endpoint in config.yaml or MCP__UPSTREAM__ENDPOINT env var.")
	}

	// Initialize management endpoints (metrics, tracing)
	mcputils.InitMetrics(cfg.Mgmt.Metrics)
	mcputils.InitTracing(cfg.Mgmt.Otel)
	defer func() {
		if err := mcputils.ShutdownTracing(context.Background()); err != nil {
			fmt.Fprintf(os.Stderr, "tracing shutdown error: %v\n", err)
		}
	}()

	switch *transport {
	case "cli":
		if flag.NArg() == 0 {
			fmt.Fprintf(os.Stderr, "Usage: %s -t cli <tool-name> [OPTIONS]\n", os.Args[0])
			fmt.Fprintf(os.Stderr, "       %s -t cli list\n", os.Args[0])
			fmt.Fprintf(os.Stderr, "\nUse -t cli <tool-name> --help for tool-specific help.\n")
			os.Exit(1)
		}
		subcmd := flag.Arg(0)
		switch subcmd {
		case "list":
			mcpcli.ListTools()
		default:
			if subcmd == "--help" || subcmd == "-h" {
				fmt.Fprintf(os.Stderr, "Usage: %s -t cli <tool-name> [OPTIONS]\n", os.Args[0])
				fmt.Fprintf(os.Stderr, "       %s -t cli list\n", os.Args[0])
				fmt.Fprintf(os.Stderr, "\nUse -t cli <tool-name> --help for tool-specific help.\n")
				os.Exit(0)
			}
			toolName := subcmd
			args := flag.Args()[1:]
			if err := mcpcli.Call(os.Args[0], toolName, args); err != nil {
				fmt.Fprintf(os.Stderr, "error: %v\n", err)
				os.Exit(1)
			}
		}

	case "http":
		s, err := mcpserver.NewMCPServer()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		mcpServer := server.NewStreamableHTTPServer(s,
			server.WithHTTPContextFunc(func(ctx context.Context, r *http.Request) context.Context {
				return mcputils.WithHTTPHeaders(ctx, r.Header)
			}),
		)

		ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
		defer cancel()

		mux := http.NewServeMux()

		// Frontend (inbound) auth: validate MCP client bearer tokens per the
		// MCP Authorization spec (2025-06-18) and RFC 9728. Only wired up for
		// the http transport — stdio has no network boundary to protect.
		var mcpHandler http.Handler = mcpServer
		if cfg.Auth.Frontend.OIDC.Enabled {
			if err := mcputils.InitFrontendAuth(ctx, cfg.Auth.Frontend.OIDC); err != nil {
				fmt.Fprintf(os.Stderr, "Error: frontend auth init failed: %v\n", err)
				os.Exit(1)
			}
			resource := mcputils.FrontendResource()
			metadataPath := server.ProtectedResourceMetadataPath(resource)
			mux.Handle(metadataPath, server.NewProtectedResourceMetadataHandler(server.ProtectedResourceMetadataConfig{
				Resource:               resource,
				AuthorizationServers:   []string{mcputils.FrontendIssuer()},
				BearerMethodsSupported: []string{"header"},
			}))
			mcpHandler = mcputils.RequireBearerToken(mcputils.ResourceMetadataURL(resource, metadataPath), mcpServer)
			fmt.Fprintf(os.Stderr, "Frontend auth enabled: issuer=%s resource=%s metadata=%s\n", mcputils.FrontendIssuer(), resource, metadataPath)
		}
		mux.Handle("/mcp", mcpHandler)

		addr := fmt.Sprintf(":%d", *port)
		httpServer := &http.Server{Addr: addr, Handler: logHTTP(mux)}

		go func() {
			fmt.Fprintf(os.Stderr, "MCP server listening on %s/mcp\n", addr)
			if err := httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
				fmt.Fprintf(os.Stderr, "HTTP server error: %v\n", err)
				os.Exit(1)
			}
		}()

		// Management server (metrics, health)
		mgmtCfg := cfg.Mgmt
		var mgmtServer *http.Server
		if mgmtCfg.IsEnabled() {
			if *metricsPort > 0 {
				mgmtCfg.Port = *metricsPort
			}
			mgmtMux := http.NewServeMux()
			if h := mcputils.MetricsHandler(); h != nil {
				mgmtMux.Handle("/metrics", h)
			}
			mgmtMux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(http.StatusOK)
				w.Write([]byte("ok"))
			})
			mgmtAddr := fmt.Sprintf("%s:%d", mgmtCfg.Host, mgmtCfg.Port)
			mgmtServer = &http.Server{Addr: mgmtAddr, Handler: mgmtMux}

			go func() {
				fmt.Fprintf(os.Stderr, "Management server listening on %s\n", mgmtAddr)
				if err := mgmtServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
					fmt.Fprintf(os.Stderr, "Management server error: %v\n", err)
				}
			}()
		}

		// pprof server
		var pprofServer *http.Server
		if mgmtCfg.Pprof.Enabled {
			pprofServer = &http.Server{Addr: mgmtCfg.Pprof.ServerBind, Handler: nil}
			go func() {
				fmt.Fprintf(os.Stderr, "pprof server listening on %s\n", mgmtCfg.Pprof.ServerBind)
				if err := pprofServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
					fmt.Fprintf(os.Stderr, "pprof server error: %v\n", err)
				}
			}()
		}

		<-ctx.Done()
		fmt.Fprintln(os.Stderr, "Shutting down...")

		// Give in-flight requests a brief grace period, then force-close.
		// SSE streaming connections (GET /mcp) never become idle, so
		// Shutdown() alone would block forever waiting for them to drain.
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer shutdownCancel()
		if err := httpServer.Shutdown(shutdownCtx); err != nil {
			httpServer.Close()
		}
		if mgmtServer != nil {
			if err := mgmtServer.Shutdown(shutdownCtx); err != nil {
				mgmtServer.Close()
			}
		}
		if pprofServer != nil {
			if err := pprofServer.Shutdown(shutdownCtx); err != nil {
				pprofServer.Close()
			}
		}

	case "stdio":
		if cfg.Auth.Frontend.OIDC.Enabled {
			fmt.Fprintln(os.Stderr, "Warning: auth.frontend.oidc is enabled but ignored under stdio transport (no network boundary to protect; the parent process already controls access to stdin/stdout).")
		}

		s, err := mcpserver.NewMCPServer()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		if err := server.ServeStdio(s); err != nil {
			fmt.Fprintf(os.Stderr, "server error: %v\n", err)
			os.Exit(1)
		}

	default:
		fmt.Fprintf(os.Stderr, "unknown transport: %s (use 'stdio', 'http', or 'cli')\n", *transport)
		os.Exit(1)
	}
}
