// Code generated by https://github.com/flowgent-labs/mcpfather

package config

import (
	"fmt"
	"os"

	"sonatypeiq-mcp/pkg/mcpvirtual/pipeline"
	"gopkg.in/yaml.v3"
)

// Config represents the virtual tools configuration.
type Config struct {
	VirtualTools []VirtualToolConfig `yaml:"virtualTools"`
}

// VirtualToolConfig defines a single virtual MCP tool.
type VirtualToolConfig struct {
	Name        string                 `yaml:"name" schema:"required"`
	Description string                 `yaml:"description"`
	Enabled     *bool                  `yaml:"enabled,omitempty"`
	Annotations map[string]interface{} `yaml:"annotations,omitempty"`
	InputSchema map[string]interface{} `yaml:"inputSchema" schema:"required"`
	Pipeline    []pipeline.StepConfig  `yaml:"pipeline" schema:"required"`
}

// LoadConfig reads and parses a config YAML file.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Config{}, nil
		}
		return nil, fmt.Errorf("failed to read config %s: %w", path, err)
	}
	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config %s: %w", path, err)
	}
	return &cfg, nil
}

// LoadConfigFromHome loads the config from $HOME/.{name}/config.yaml.
func LoadConfigFromHome(name string) (*Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return &Config{}, nil
	}
	return LoadConfig(home + "/." + name + "/config.yaml")
}
