// Code generated by https://github.com/flowgent-labs/mcpfather

package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadConfig_Valid(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	content := `
virtualTools:
  - name: test_tool
    description: A test virtual tool
    inputSchema:
      type: object
      properties:
        id:
          type: string
    pipeline:
      - id: step1
        kind: call
        spec:
          tool: native_tool
          args:
            id: $input.id
      - id: done
        kind: return
        spec:
          from: $step1
`
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	cfg, err := LoadConfig(path)
	if err != nil {
		t.Fatalf("LoadConfig failed: %v", err)
	}
	if len(cfg.VirtualTools) != 1 {
		t.Fatalf("expected 1 tool, got %d", len(cfg.VirtualTools))
	}
	tool := cfg.VirtualTools[0]
	if tool.Name != "test_tool" {
		t.Errorf("name = %q, want %q", tool.Name, "test_tool")
	}
	if len(tool.Pipeline) != 2 {
		t.Errorf("expected 2 pipeline steps, got %d", len(tool.Pipeline))
	}
}

func TestLoadConfig_Empty(t *testing.T) {
	cfg, err := LoadConfig("/nonexistent/path/config.yaml")
	if err != nil {
		t.Fatalf("LoadConfig should not error for missing file: %v", err)
	}
	if cfg == nil {
		t.Fatal("expected non-nil config")
	}
	if len(cfg.VirtualTools) != 0 {
		t.Errorf("expected 0 tools, got %d", len(cfg.VirtualTools))
	}
}

func TestLoadConfig_WithAnnotations(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	content := `
virtualTools:
  - name: mytool
    description: "Test"
    annotations:
      readOnlyHint: true
      destructiveHint: false
    inputSchema:
      type: object
      properties:
        id:
          type: string
    pipeline:
      - id: step1
        kind: return
        spec:
          from: $input.id
`
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	cfg, err := LoadConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.VirtualTools[0].Annotations["readOnlyHint"] != true {
		t.Errorf("expected readOnlyHint=true, got %v", cfg.VirtualTools[0].Annotations["readOnlyHint"])
	}
}
