// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the AddRepositoryManager tool
const AddRepositoryManagerInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"Enter values for the new repository manager.\",\n      \"properties\": {\n        \"id\": {\n          \"type\": \"string\"\n        },\n        \"instanceId\": {\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"type\": \"string\"\n        },\n        \"productName\": {\n          \"type\": \"string\"\n        },\n        \"productVersion\": {\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the AddRepositoryManager tool (Status: 200, Content-Type: application/json)
const AddRepositoryManagerResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains the details of the new repository manager.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **id** (Type: string):\n  - **instanceId** (Type: string):\n  - **name** (Type: string):\n  - **productName** (Type: string):\n  - **productVersion** (Type: string):\n"

// NewAddRepositoryManagerMCPTool creates the MCP Tool instance for AddRepositoryManager
func NewAddRepositoryManagerMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"AddRepositoryManager",
		"Use this method to add a new repository manager.\n\nPermissions required: Edit IQ Elements",
		[]byte(AddRepositoryManagerInputSchema),
	)
}

// AddRepositoryManagerHandler is the handler function for the AddRepositoryManager tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func AddRepositoryManagerHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/firewall/repositoryManagers", args, []string{}, contentType, "AddRepositoryManager")
}
