// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSearchIndexAsync tool
const CreateSearchIndexAsyncInputSchema = "{\n  \"type\": \"object\"\n}"

// NewCreateSearchIndexAsyncMCPTool creates the MCP Tool instance for CreateSearchIndexAsync
func NewCreateSearchIndexAsyncMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSearchIndexAsync",
		"Use this method to create or rebuild the index for Advanced Search. This is a resource intensive operation. Avoid creating indexes during peak usage hours.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(CreateSearchIndexAsyncInputSchema),
	)
}

// CreateSearchIndexAsyncHandler is the handler function for the CreateSearchIndexAsync tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSearchIndexAsyncHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/search/advanced/index", args, []string{}, contentType, "CreateSearchIndexAsync")
}
