// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteAttributionReportTemplate tool
const DeleteAttributionReportTemplateInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Enter the template id for the template to be deleted.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteAttributionReportTemplateMCPTool creates the MCP Tool instance for DeleteAttributionReportTemplate
func NewDeleteAttributionReportTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteAttributionReportTemplate",
		"Use this method to delete an existing template.\n\nPermissions required: Review Legal Obligations For Components Licenses for the root organization",
		[]byte(DeleteAttributionReportTemplateInputSchema),
	)
}

// DeleteAttributionReportTemplateHandler is the handler function for the DeleteAttributionReportTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteAttributionReportTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/licenseLegalMetadata/report-template/{id}", args, []string{"id"}, contentType, "DeleteAttributionReportTemplate")
}
