// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteUserMappings tool
const DeleteUserMappingsInputSchema = "{\n  \"properties\": {\n    \"organizationId\": {\n      \"description\": \"Enter the organizationId.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"organizationId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteUserMappingsMCPTool creates the MCP Tool instance for DeleteUserMappings
func NewDeleteUserMappingsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteUserMappings",
		"Use this method to delete existing SCM user mappings for an organization.\n\nPermissions required: Edit IQ Elements",
		[]byte(DeleteUserMappingsInputSchema),
	)
}

// DeleteUserMappingsHandler is the handler function for the DeleteUserMappings tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteUserMappingsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/sourceControl/automaticRoleAssignment/userMappings/{organizationId}", args, []string{"organizationId"}, contentType, "DeleteUserMappings")
}
