// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteConfiguration tool
const DeleteConfigurationInputSchema = "{\n  \"properties\": {\n    \"ownerId\": {\n      \"description\": \"The internal ID of the owner\",\n      \"type\": \"string\"\n    },\n    \"ownerType\": {\n      \"description\": \"The owner type (application or organization)\",\n      \"enum\": [\n        \"application\",\n        \"organization\"\n      ],\n      \"pattern\": \"application|organization\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"ownerId\",\n    \"ownerType\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteConfigurationMCPTool creates the MCP Tool instance for DeleteConfiguration
func NewDeleteConfigurationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteConfiguration",
		"Use this method to delete CI integration configuration for the specified owner.\n\nPermissions required: Edit IQ Elements",
		[]byte(DeleteConfigurationInputSchema),
	)
}

// DeleteConfigurationHandler is the handler function for the DeleteConfiguration tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteConfigurationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/config/ci/{ownerType}/{ownerId}", args, []string{"ownerId", "ownerType"}, contentType, "DeleteConfiguration")
}
