// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRepositoryManager tool
const DeleteRepositoryManagerInputSchema = "{\n  \"properties\": {\n    \"repositoryManagerId\": {\n      \"description\": \"Enter the repository manager ID.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryManagerId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRepositoryManagerMCPTool creates the MCP Tool instance for DeleteRepositoryManager
func NewDeleteRepositoryManagerMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRepositoryManager",
		"Use this method to delete an existing repository manager.\n\nPermissions required: Edit IQ Elements",
		[]byte(DeleteRepositoryManagerInputSchema),
	)
}

// DeleteRepositoryManagerHandler is the handler function for the DeleteRepositoryManager tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRepositoryManagerHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/firewall/repositoryManagers/{repositoryManagerId}", args, []string{"repositoryManagerId"}, contentType, "DeleteRepositoryManager")
}
