// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteConfiguration5 tool
const DeleteConfiguration5InputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteConfiguration5MCPTool creates the MCP Tool instance for DeleteConfiguration5
func NewDeleteConfiguration5MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteConfiguration5",
		"Use this method to remove an existing reverse proxy server configuration.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(DeleteConfiguration5InputSchema),
	)
}

// DeleteConfiguration5Handler is the handler function for the DeleteConfiguration5 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteConfiguration5Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/config/reverseProxyAuthentication", args, []string{}, contentType, "DeleteConfiguration5")
}
