// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRole tool
const DeleteRoleInputSchema = "{\n  \"properties\": {\n    \"roleId\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"roleId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRoleMCPTool creates the MCP Tool instance for DeleteRole
func NewDeleteRoleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRole",
		"Use this method to delete a custom role.\n\nPermissions required: Edit Roles",
		[]byte(DeleteRoleInputSchema),
	)
}

// DeleteRoleHandler is the handler function for the DeleteRole tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRoleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/roles/{roleId}", args, []string{"roleId"}, contentType, "DeleteRole")
}
