// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteCurrentUserToken tool
const DeleteCurrentUserTokenInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteCurrentUserTokenMCPTool creates the MCP Tool instance for DeleteCurrentUserToken
func NewDeleteCurrentUserTokenMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteCurrentUserToken",
		"Use this method to delete an existing user token for the currently logged in user.\n\nPermissions required: None",
		[]byte(DeleteCurrentUserTokenInputSchema),
	)
}

// DeleteCurrentUserTokenHandler is the handler function for the DeleteCurrentUserToken tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteCurrentUserTokenHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/userTokens/currentUser", args, []string{}, contentType, "DeleteCurrentUserToken")
}
