// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteLabel tool
const DeleteLabelInputSchema = "{\n  \"properties\": {\n    \"labelId\": {\n      \"description\": \"Enter the id for the label to be deleted.\",\n      \"type\": \"string\"\n    },\n    \"ownerId\": {\n      \"description\": \"Enter the id for the selected ownerType.\",\n      \"type\": \"string\"\n    },\n    \"ownerType\": {\n      \"description\": \"Select the ownerType for which the label will be deleted.\",\n      \"enum\": [\n        \"application\",\n        \"organization\",\n        \"repository_container\",\n        \"repository_manager\",\n        \"repository\"\n      ],\n      \"pattern\": \"application|organization|repository|repository_manager|repository_container\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"labelId\",\n    \"ownerId\",\n    \"ownerType\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteLabelMCPTool creates the MCP Tool instance for DeleteLabel
func NewDeleteLabelMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteLabel",
		"Use this method to delete an existing component label.\n\nPermissions required: Edit IQ Elements",
		[]byte(DeleteLabelInputSchema),
	)
}

// DeleteLabelHandler is the handler function for the DeleteLabel tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteLabelHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/labels/{ownerType}/{ownerId}/{labelId}", args, []string{"labelId", "ownerId", "ownerType"}, contentType, "DeleteLabel")
}
