// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteLicenseOverride tool
const DeleteLicenseOverrideInputSchema = "{\n  \"properties\": {\n    \"licenseOverrideId\": {\n      \"description\": \"Enter the id of the license override you want to delete.\",\n      \"type\": \"string\"\n    },\n    \"ownerId\": {\n      \"description\": \"Enter the id of the application, organization or the repository.\",\n      \"type\": \"string\"\n    },\n    \"ownerType\": {\n      \"description\": \"Select the " + "\x60" + "ownerType" + "\x60" + " scope for which you want to delete license override\",\n      \"enum\": [\n        \"application\",\n        \"organization\",\n        \"repository_container\",\n        \"repository_manager\",\n        \"repository\"\n      ],\n      \"pattern\": \"application|organization|repository|repository_manager|repository_container\",\n      \"type\": \"string\"\n    },\n    \"where\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"licenseOverrideId\",\n    \"ownerId\",\n    \"ownerType\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteLicenseOverrideMCPTool creates the MCP Tool instance for DeleteLicenseOverride
func NewDeleteLicenseOverrideMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteLicenseOverride",
		"Use this method to delete a license override for a component.\n\nPermissions required: Change Licenses",
		[]byte(DeleteLicenseOverrideInputSchema),
	)
}

// DeleteLicenseOverrideHandler is the handler function for the DeleteLicenseOverride tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteLicenseOverrideHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/licenseOverrides/{ownerType}/{ownerId}/{licenseOverrideId}", args, []string{"licenseOverrideId", "ownerId", "ownerType"}, contentType, "DeleteLicenseOverride")
}
