// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteUserTokenByUserCode tool
const DeleteUserTokenByUserCodeInputSchema = "{\n  \"properties\": {\n    \"userCode\": {\n      \"description\": \"Enter the " + "\x60" + "userCode" + "\x60" + " to be deleted.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"userCode\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteUserTokenByUserCodeMCPTool creates the MCP Tool instance for DeleteUserTokenByUserCode
func NewDeleteUserTokenByUserCodeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteUserTokenByUserCode",
		"Use this method to delete an existing user token by specifying the userCode.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(DeleteUserTokenByUserCodeInputSchema),
	)
}

// DeleteUserTokenByUserCodeHandler is the handler function for the DeleteUserTokenByUserCode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteUserTokenByUserCodeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/userTokens/userCode/{userCode}", args, []string{"userCode"}, contentType, "DeleteUserTokenByUserCode")
}
