// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DisableFeature tool
const DisableFeatureInputSchema = "{\n  \"properties\": {\n    \"feature\": {\n      \"description\": \"Enter the name of the IQ Server feature to be disabled.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"feature\"\n  ],\n  \"type\": \"object\"\n}"

// NewDisableFeatureMCPTool creates the MCP Tool instance for DisableFeature
func NewDisableFeatureMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DisableFeature",
		"Use this method to disable an IQ Server feature.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(DisableFeatureInputSchema),
	)
}

// DisableFeatureHandler is the handler function for the DisableFeature tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DisableFeatureHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/config/features/{feature}", args, []string{"feature"}, contentType, "DisableFeature")
}
