// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the EnabledFeature tool
const EnabledFeatureInputSchema = "{\n  \"properties\": {\n    \"feature\": {\n      \"description\": \"Enter the name of the feature to be enabled.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"feature\"\n  ],\n  \"type\": \"object\"\n}"

// NewEnabledFeatureMCPTool creates the MCP Tool instance for EnabledFeature
func NewEnabledFeatureMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"EnabledFeature",
		"Use this method to enable an IQ Server feature.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(EnabledFeatureInputSchema),
	)
}

// EnabledFeatureHandler is the handler function for the EnabledFeature tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func EnabledFeatureHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/config/features/{feature}", args, []string{"feature"}, contentType, "EnabledFeature")
}
