// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GenerateManifest tool
const GenerateManifestInputSchema = "{\n  \"properties\": {\n    \"organizationName\": {\n      \"description\": \"GitHub organization name\",\n      \"type\": \"string\"\n    },\n    \"ownerId\": {\n      \"description\": \"Owner (organization/application) ID\",\n      \"minLength\": 1,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"ownerId\"\n  ],\n  \"type\": \"object\"\n}"

// NewGenerateManifestMCPTool creates the MCP Tool instance for GenerateManifest
func NewGenerateManifestMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GenerateManifest",
		"Generate GitHub App manifest - Generate a GitHub App manifest for registration. Returns manifest JSON with a state token for CSRF protection. The state token is cryptographically secure, single-use, and expires after 10 minutes. Submit the manifest to GitHub's app creation flow, which will redirect back to IQ Server with the state token for validation. \n\n**Permissions Required:** Configure System Configuration and Users",
		[]byte(GenerateManifestInputSchema),
	)
}

// GenerateManifestHandler is the handler function for the GenerateManifest tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GenerateManifestHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/githubApp/manifest", args, []string{}, contentType, "GenerateManifest")
}
