// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAll2 tool
const GetAll2InputSchema = "{\n  \"properties\": {\n    \"realm\": {\n      \"default\": \"Internal\",\n      \"description\": \"Enter the " + "\x60" + "realm" + "\x60" + ". Allowed values are " + "\x60" + "Internal" + "\x60" + "," + "\x60" + "OAUTH2" + "\x60" + ", and " + "\x60" + "SAML" + "\x60" + ".\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetAll2 tool (Status: 200, Content-Type: application/json)
const GetAll2ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains user details. Passwords are excluded for security.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **users** (Type: array):\n    - **Items** (Type: object):\n      - **email** (Type: string):\n      - **firstName** (Type: string):\n      - **lastName** (Type: string):\n      - **password** (Type: string):\n      - **realm** (Type: string):\n      - **username** (Type: string):\n"

// NewGetAll2MCPTool creates the MCP Tool instance for GetAll2
func NewGetAll2MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAll2",
		"Use this method to retrieve user details for all users.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(GetAll2InputSchema),
	)
}

// GetAll2Handler is the handler function for the GetAll2 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAll2Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/users", args, []string{}, contentType, "GetAll2")
}
