// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAll tool
const GetAllInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetAll tool (Status: 200, Content-Type: application/json)
const GetAllResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains the truncated SHA1 hash of each component, the datetime when the component was published (not the time it was claimed), the format and coordinates of the claimed component (componentIdentifier) and the package URL of the claimed component.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **componentClaims** (Type: array):\n    - **Items** (Type: object):\n      - **claimerId** (Type: string):\n      - **claimerName** (Type: string):\n      - **comment** (Type: string):\n      - **componentIdentifier** (Type: object):\n        - **coordinates** (Type: object):\n          - **Additional Properties**:\n            - **property value** (Type: string):\n        - **format** (Type: string):\n      - **createTime** (Type: string, date-time):\n      - **hash** (Type: string):\n      - **packageUrl** (Type: string):\n"

// NewGetAllMCPTool creates the MCP Tool instance for GetAll
func NewGetAllMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAll",
		"Use this method to retrieve details of all claimed components.\n\nPermissions required: Claim components",
		[]byte(GetAllInputSchema),
	)
}

// GetAllHandler is the handler function for the GetAll tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAllHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/claim/components", args, []string{}, contentType, "GetAll")
}
