// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetApplicationApplicableTags tool
const GetApplicationApplicableTagsInputSchema = "{\n  \"properties\": {\n    \"applicationPublicId\": {\n      \"description\": \"The application public ID \",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"applicationPublicId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetApplicationApplicableTags tool (Status: 200, Content-Type: application/json)
const GetApplicationApplicableTagsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> A list of application categories that can be applied to the specified application. Each application category or tag consists of an id, name, description and color. \n\n## Response Structure\n\n- Structure (Type: object):\n  - **applicationCategoriesByOwner** (Type: array):\n    - **Items** (Type: object):\n      - **applicationCategories** (Type: array):\n        - **Items** (Type: object):\n          - **color** (Type: string):\n          - **description** (Type: string):\n          - **id** (Type: string):\n          - **name** (Type: string):\n          - **organizationId** (Type: string):\n      - **ownerId** (Type: string):\n      - **ownerName** (Type: string):\n      - **ownerType** (Type: string):\n          - Enum: ['application', 'organization', 'repository_container', 'repository_manager', 'repository', 'global']\n"

// NewGetApplicationApplicableTagsMCPTool creates the MCP Tool instance for GetApplicationApplicableTags
func NewGetApplicationApplicableTagsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetApplicationApplicableTags",
		"Grouping applications with similar characteristics into categories makes policy management easier. You can then create a policy that applies to a specific category. Use this method to retrieve a list of application categories available to applications in this organization.",
		[]byte(GetApplicationApplicableTagsInputSchema),
	)
}

// GetApplicationApplicableTagsHandler is the handler function for the GetApplicationApplicableTags tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetApplicationApplicableTagsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/applicationCategories/application/{applicationPublicId}", args, []string{"applicationPublicId"}, contentType, "GetApplicationApplicableTags")
}
