// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAll1 tool
const GetAll1InputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetAll1 tool (Status: 200, Content-Type: application/json)
const GetAll1ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response JSON contains URLs to view the report data in html and pdf format, for each application to which you have access.\n\nThe response field stage indicates the stage at which the policy evaluation was executed, such as 'develop', 'build' and 'release' The response field latestReportHtmlUrl is a relative link to view the most recent report. Response fields reportPdfUrl and reportHtmlUrl are links to view the pdf version of the report.The response field reportDataUrl is a link to view the most recent report data. \n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **applicationId** (Type: string):\n    - **embeddableReportHtmlUrl** (Type: string):\n    - **evaluationDate** (Type: string, date-time):\n    - **latestReportHtmlUrl** (Type: string):\n    - **reportDataUrl** (Type: string):\n    - **reportHtmlUrl** (Type: string):\n    - **reportPdfUrl** (Type: string):\n    - **stage** (Type: string):\n"

// NewGetAll1MCPTool creates the MCP Tool instance for GetAll1
func NewGetAll1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAll1",
		"Use this method to view all application reports for applications to which  you have access. \n\nPermissions required: View IQ Elements ",
		[]byte(GetAll1InputSchema),
	)
}

// GetAll1Handler is the handler function for the GetAll1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAll1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/reports/applications", args, []string{}, contentType, "GetAll1")
}
