// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAppliedPolicyTags tool
const GetAppliedPolicyTagsInputSchema = "{\n  \"properties\": {\n    \"organizationId\": {\n      \"description\": \"The organizationId assigned by IQ Server.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"organizationId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetAppliedPolicyTags tool (Status: 200, Content-Type: application/json)
const GetAppliedPolicyTagsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Get all policy application categories or tags that are applied to applications  in this organization.\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **id** (Type: string):\n    - **policyId** (Type: string):\n    - **tagId** (Type: string):\n"

// NewGetAppliedPolicyTagsMCPTool creates the MCP Tool instance for GetAppliedPolicyTags
func NewGetAppliedPolicyTagsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAppliedPolicyTags",
		"Grouping applications with similar characteristics into categories makes policy management easier. You can then create a policy that applies to a specific category. Use this method to retrieve a list of application categories that are applied to applications in this organization.",
		[]byte(GetAppliedPolicyTagsInputSchema),
	)
}

// GetAppliedPolicyTagsHandler is the handler function for the GetAppliedPolicyTags tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAppliedPolicyTagsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/applicationCategories/organization/{organizationId}/policy", args, []string{"organizationId"}, contentType, "GetAppliedPolicyTags")
}
