// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAuditLogs tool
const GetAuditLogsInputSchema = "{\n  \"properties\": {\n    \"endUtcDate\": {\n      \"description\": \"Enter the end UTC date in the format (yyyy-mm-dd).\",\n      \"type\": \"string\"\n    },\n    \"startUtcDate\": {\n      \"description\": \"Enter the start UTC date in the format (yyyy-mm-dd).\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewGetAuditLogsMCPTool creates the MCP Tool instance for GetAuditLogs
func NewGetAuditLogsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAuditLogs",
		"Use this method to retrieve the audit events for the specified time period.\n\nPermissions required: Access Audit Log",
		[]byte(GetAuditLogsInputSchema),
	)
}

// GetAuditLogsHandler is the handler function for the GetAuditLogs tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAuditLogsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/auditLogs", args, []string{}, contentType, "GetAuditLogs")
}
