// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetConfiguration7 tool
const GetConfiguration7InputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetConfiguration7 tool (Status: 200, Content-Type: application/json)
const GetConfiguration7ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Current user token configuration\n\n## Response Structure\n\n- Structure (Type: object):\n  - **userTokenDefaultExpirationDays** (Type: integer, int32):\n"

// NewGetConfiguration7MCPTool creates the MCP Tool instance for GetConfiguration7
func NewGetConfiguration7MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetConfiguration7",
		"Use this method to retrieve user token configuration.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(GetConfiguration7InputSchema),
	)
}

// GetConfiguration7Handler is the handler function for the GetConfiguration7 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetConfiguration7Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/config/userTokens", args, []string{}, contentType, "GetConfiguration7")
}
