// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetCurrentUserTokenCreateTime tool
const GetCurrentUserTokenCreateTimeInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetCurrentUserTokenCreateTime tool (Status: 200, Content-Type: application/json)
const GetCurrentUserTokenCreateTimeResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains the token creation time in ISO format.\n\n## Response Structure\n\n- Structure (Type: string, date-time):\n"

// NewGetCurrentUserTokenCreateTimeMCPTool creates the MCP Tool instance for GetCurrentUserTokenCreateTime
func NewGetCurrentUserTokenCreateTimeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetCurrentUserTokenCreateTime",
		"Use this method to retrieve the creation time of the user token for the currently logged in user.\n\nPermissions required: None",
		[]byte(GetCurrentUserTokenCreateTimeInputSchema),
	)
}

// GetCurrentUserTokenCreateTimeHandler is the handler function for the GetCurrentUserTokenCreateTime tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetCurrentUserTokenCreateTimeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/userTokens/currentUser/createTime", args, []string{}, contentType, "GetCurrentUserTokenCreateTime")
}
