// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetExportResults tool
const GetExportResultsInputSchema = "{\n  \"properties\": {\n    \"allComponents\": {\n      \"default\": false,\n      \"description\": \"Set to " + "\x60" + "true" + "\x60" + " to retrieve results that include components with no violations.\",\n      \"type\": \"boolean\"\n    },\n    \"mode\": {\n      \"enum\": [\n        \"sbomManager\"\n      ],\n      \"type\": \"string\"\n    },\n    \"page\": {\n      \"description\": \"Enter the page no. for the page containing results\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"pageSize\": {\n      \"description\": \"Enter the no. of results that should be visible per page, unset gives all results\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"query\": {\n      \"description\": \"A well-formed search query.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"query\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetExportResultsMCPTool creates the MCP Tool instance for GetExportResults
func NewGetExportResultsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetExportResults",
		"Use this method to generate a csv file containing your search results. The default delimiter in the generated file is comma. Use the advancedSearchCSVExportDelimiter property of the Configuration REST API to change the delimiter in the generated file.",
		[]byte(GetExportResultsInputSchema),
	)
}

// GetExportResultsHandler is the handler function for the GetExportResults tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetExportResultsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/search/advanced/export/csv", args, []string{}, contentType, "GetExportResults")
}
