// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetFirewallMetrics tool
const GetFirewallMetricsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetFirewallMetrics tool (Status: 200, Content-Type: application/json)
const GetFirewallMetricsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains a map of firewall metric name to value including the last updated time.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **Additional Properties**:\n    - **property value** (Type: object):\n      - **firewallMetricsValue** (Type: integer, int32):\n      - **latestUpdatedTime** (Type: string, date-time):\n"

// NewGetFirewallMetricsMCPTool creates the MCP Tool instance for GetFirewallMetrics
func NewGetFirewallMetricsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetFirewallMetrics",
		"Use this method to retrieve firewall dashboard metrics.\n\nPermissions required: View IQ Elements",
		[]byte(GetFirewallMetricsInputSchema),
	)
}

// GetFirewallMetricsHandler is the handler function for the GetFirewallMetrics tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetFirewallMetricsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/firewall/metrics/embedded", args, []string{}, contentType, "GetFirewallMetrics")
}
