// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetLicenseLegalMultiApplicationHtmlreport tool
const GetLicenseLegalMultiApplicationHtmlreportInputSchema = "{\n  \"type\": \"object\"\n}"

// NewGetLicenseLegalMultiApplicationHtmlreportMCPTool creates the MCP Tool instance for GetLicenseLegalMultiApplicationHtmlreport
func NewGetLicenseLegalMultiApplicationHtmlreportMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetLicenseLegalMultiApplicationHtmlreport",
		"Use this method to generate license legal data in HTML format.\n\nPermissions required: Review Legal Obligations For Components Licenses",
		[]byte(GetLicenseLegalMultiApplicationHtmlreportInputSchema),
	)
}

// GetLicenseLegalMultiApplicationHtmlreportHandler is the handler function for the GetLicenseLegalMultiApplicationHtmlreport tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetLicenseLegalMultiApplicationHtmlreportHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/licenseLegalMetadata/multiApplication/report", args, []string{}, contentType, "GetLicenseLegalMultiApplicationHtmlreport")
}
