// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetLicenseLegalCustomMultiApplicationHtmlreport1 tool
const GetLicenseLegalCustomMultiApplicationHtmlreport1InputSchema = "{\n  \"properties\": {\n    \"templateId\": {\n      \"description\": \"Enter the " + "\x60" + "templateId" + "\x60" + " for the HTML report.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"templateId\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetLicenseLegalCustomMultiApplicationHtmlreport1MCPTool creates the MCP Tool instance for GetLicenseLegalCustomMultiApplicationHtmlreport1
func NewGetLicenseLegalCustomMultiApplicationHtmlreport1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetLicenseLegalCustomMultiApplicationHtmlreport1",
		"Use this method to generate license legal data for all applications in HTML format based on the given template.\n\nPermissions required: Review Legal Obligations For Components Licenses",
		[]byte(GetLicenseLegalCustomMultiApplicationHtmlreport1InputSchema),
	)
}

// GetLicenseLegalCustomMultiApplicationHtmlreport1Handler is the handler function for the GetLicenseLegalCustomMultiApplicationHtmlreport1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetLicenseLegalCustomMultiApplicationHtmlreport1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/licenseLegalMetadata/multiApplication/report/templateId/{templateId}", args, []string{"templateId"}, contentType, "GetLicenseLegalCustomMultiApplicationHtmlreport1")
}
