// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetLicensedSolutions tool
const GetLicensedSolutionsInputSchema = "{\n  \"properties\": {\n    \"allowRelativeUrls\": {\n      \"default\": false,\n      \"description\": \"Whether or not relative URLs should be allowed.\",\n      \"type\": \"boolean\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetLicensedSolutions tool (Status: 200, Content-Type: application/json)
const GetLicensedSolutionsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successfully retrieved the list of licensed solutions.\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **id** (Type: string):\n    - **url** (Type: string):\n"

// NewGetLicensedSolutionsMCPTool creates the MCP Tool instance for GetLicensedSolutions
func NewGetLicensedSolutionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetLicensedSolutions",
		"Retrieves a list of licensed solutions. The base URL must be set to get results unless relative URLs are allowed.\n\nPermissions required: None ",
		[]byte(GetLicensedSolutionsInputSchema),
	)
}

// GetLicensedSolutionsHandler is the handler function for the GetLicensedSolutions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetLicensedSolutionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/solutions/licensed", args, []string{}, contentType, "GetLicensedSolutions")
}
