// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetLicenseLegalCustomApplicationHtmlreport1 tool
const GetLicenseLegalCustomApplicationHtmlreport1InputSchema = "{\n  \"properties\": {\n    \"applicationId\": {\n      \"description\": \"Enter the application id or public id.\",\n      \"type\": \"string\"\n    },\n    \"stageId\": {\n      \"description\": \"Enter the stageId.\",\n      \"type\": \"string\"\n    },\n    \"templateId\": {\n      \"description\": \"Enter the templateId for the HTML report format.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"applicationId\",\n    \"stageId\",\n    \"templateId\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetLicenseLegalCustomApplicationHtmlreport1MCPTool creates the MCP Tool instance for GetLicenseLegalCustomApplicationHtmlreport1
func NewGetLicenseLegalCustomApplicationHtmlreport1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetLicenseLegalCustomApplicationHtmlreport1",
		"Use this method to generate a license legal report in the specified HTML template format.\n\nPermissions required: Review Legal Obligations For Components Licenses",
		[]byte(GetLicenseLegalCustomApplicationHtmlreport1InputSchema),
	)
}

// GetLicenseLegalCustomApplicationHtmlreport1Handler is the handler function for the GetLicenseLegalCustomApplicationHtmlreport1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetLicenseLegalCustomApplicationHtmlreport1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/licenseLegalMetadata/application/{applicationId}/stage/{stageId}/report/templateId/{templateId}", args, []string{"applicationId", "stageId", "templateId"}, contentType, "GetLicenseLegalCustomApplicationHtmlreport1")
}
