// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetMetadata tool
const GetMetadataInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetMetadata tool (Status: 200, Content-Type: application/xml)
const GetMetadataResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/xml\n\n> The IQ Server's metadata service provider descriptor in XML format.\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewGetMetadataMCPTool creates the MCP Tool instance for GetMetadata
func NewGetMetadataMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMetadata",
		"Use this method to retrieve IQ Server's metadata service provider descriptor.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(GetMetadataInputSchema),
	)
}

// GetMetadataHandler is the handler function for the GetMetadata tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMetadataHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/config/saml/metadata", args, []string{}, contentType, "GetMetadata")
}
