// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetOwnerArtifactoryConnection tool
const GetOwnerArtifactoryConnectionInputSchema = "{\n  \"properties\": {\n    \"inherit\": {\n      \"default\": false,\n      \"description\": \"Specify whether to include details from an inherited Artifactory connection.\",\n      \"type\": \"boolean\"\n    },\n    \"internalOwnerId\": {\n      \"description\": \"Enter the internal ID of the owner.\",\n      \"type\": \"string\"\n    },\n    \"ownerType\": {\n      \"description\": \"Select the owner type.\",\n      \"enum\": [\n        \"application\",\n        \"organization\"\n      ],\n      \"pattern\": \"application|organization\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"internalOwnerId\",\n    \"ownerType\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetOwnerArtifactoryConnection tool (Status: 200, Content-Type: application/json)
const GetOwnerArtifactoryConnectionResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains the details of the Artifactory connection.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **artifactoryConnection** (Type: object):\n    - **artifactoryConnectionId** (Type: string):\n    - **baseUrl** (Type: string):\n    - **isAnonymous** (Type: boolean):\n    - **ownerId** (Type: string):\n    - **ownerType** (Type: string):\n        - Enum: ['application', 'organization', 'repository_container', 'repository_manager', 'repository', 'global']\n    - **password** (Type: string):\n    - **username** (Type: string):\n  - **artifactoryConnectionStatus** (Type: object):\n    - **allowChange** (Type: boolean):\n    - **allowOverride** (Type: boolean):\n    - **enabled** (Type: boolean):\n    - **inheritedFromOrgEnabled** (Type: boolean):\n    - **inheritedFromOrganizationId** (Type: string):\n    - **inheritedFromOrganizationName** (Type: string):\n  - **ownerDTO** (Type: object):\n    - **ownerId** (Type: string):\n    - **ownerName** (Type: string):\n    - **ownerPublicId** (Type: string):\n    - **ownerType** (Type: string):\n"

// NewGetOwnerArtifactoryConnectionMCPTool creates the MCP Tool instance for GetOwnerArtifactoryConnection
func NewGetOwnerArtifactoryConnectionMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetOwnerArtifactoryConnection",
		"Use this method to retrieve Artifactory connection details by specifying the owner Id.\n\nPermissions required: View IQ Elements",
		[]byte(GetOwnerArtifactoryConnectionInputSchema),
	)
}

// GetOwnerArtifactoryConnectionHandler is the handler function for the GetOwnerArtifactoryConnection tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetOwnerArtifactoryConnectionHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/config/artifactoryConnection/{ownerType}/{internalOwnerId}", args, []string{"internalOwnerId", "ownerType"}, contentType, "GetOwnerArtifactoryConnection")
}
