// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPolicyWaiverReasons tool
const GetPolicyWaiverReasonsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetPolicyWaiverReasons tool (Status: 200, Content-Type: application/json)
const GetPolicyWaiverReasonsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successfully retrieved all policy waiver reasons.\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **id** (Type: string):\n    - **reasonText** (Type: string):\n    - **type** (Type: string):\n"

// NewGetPolicyWaiverReasonsMCPTool creates the MCP Tool instance for GetPolicyWaiverReasons
func NewGetPolicyWaiverReasonsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPolicyWaiverReasons",
		"Use this method to retrieve all policy waiver reasons.\n\nPermissions required: None",
		[]byte(GetPolicyWaiverReasonsInputSchema),
	)
}

// GetPolicyWaiverReasonsHandler is the handler function for the GetPolicyWaiverReasons tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPolicyWaiverReasonsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/policyWaiverReasons", args, []string{}, contentType, "GetPolicyWaiverReasons")
}
