// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetScanStatus tool
const GetScanStatusInputSchema = "{\n  \"properties\": {\n    \"applicationId\": {\n      \"description\": \"Enter the application internal id for the SBOM to be evaluated.\",\n      \"type\": \"string\"\n    },\n    \"scanRequestId\": {\n      \"description\": \"Enter the statusId from the statusUrl generated as a response to the POST request to perform the evaluation.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"applicationId\",\n    \"scanRequestId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetScanStatus tool (Status: 200, Content-Type: application/json)
const GetScanStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The response contains summarized results of the SBOM evaluation and the URLs for detailed evaluation reports in HTML, pdf and raw formats.\n\n" + "\x60" + "policyAction" + "\x60" + " indicates the policy actions determined by the " + "\x60" + "stageId" + "\x60" + " selected while submitting the evaluation using the POST method.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **componentsAffected** (Type: object):\n    - **critical** (Type: integer, int32):\n    - **moderate** (Type: integer, int32):\n    - **severe** (Type: integer, int32):\n  - **embeddableReportHtmlUrl** (Type: string):\n  - **errorMessage** (Type: string):\n  - **grandfatheredPolicyViolations** (Type: integer, int32):\n  - **isError** (Type: boolean):\n  - **legacyViolations** (Type: integer, int32):\n  - **[cyclic reference]**\n  - **policyAction** (Type: string):\n  - **reportDataUrl** (Type: string):\n  - **reportHtmlUrl** (Type: string):\n  - **reportPdfUrl** (Type: string):\n"

// NewGetScanStatusMCPTool creates the MCP Tool instance for GetScanStatus
func NewGetScanStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetScanStatus",
		"SBOM evaluation is an asynchronous operation. Use this method to check on the status of the SBOM evaluation.\n\nPermissions required: Evaluate Applications",
		[]byte(GetScanStatusInputSchema),
	)
}

// GetScanStatusHandler is the handler function for the GetScanStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetScanStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/scan/applications/{applicationId}/status/{scanRequestId}", args, []string{"applicationId", "scanRequestId"}, contentType, "GetScanStatus")
}
