// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the HandleRedirect tool
const HandleRedirectInputSchema = "{\n  \"properties\": {\n    \"code\": {\n      \"description\": \"Temporary manifest conversion code from GitHub\",\n      \"type\": \"string\"\n    },\n    \"state\": {\n      \"description\": \"OAuth state token for CSRF protection\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"code\"\n  ],\n  \"type\": \"object\"\n}"

// NewHandleRedirectMCPTool creates the MCP Tool instance for HandleRedirect
func NewHandleRedirectMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"HandleRedirect",
		"GitHub App registration redirect callback - Handles redirect from GitHub after manifest submission. Exchanges temporary code for permanent app credentials. The user's browser is automatically redirected here by GitHub - not intended for direct use. **Permissions Required:** Configure System Configuration and Users",
		[]byte(HandleRedirectInputSchema),
	)
}

// HandleRedirectHandler is the handler function for the HandleRedirect tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func HandleRedirectHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/v2/githubApp/redirect", args, []string{}, contentType, "HandleRedirect")
}
