// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the InstallLicense tool
const InstallLicenseInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"file\": {\n          \"description\": \"Your product license file\",\n          \"format\": \"binary\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"file\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewInstallLicenseMCPTool creates the MCP Tool instance for InstallLicense
func NewInstallLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"InstallLicense",
		"Use this method to install a product license\n\nPermissions required: Edit System Configuration and Users",
		[]byte(InstallLicenseInputSchema),
	)
}

// InstallLicenseHandler is the handler function for the InstallLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func InstallLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	fileName := ""
	if fn, ok := args["file_name"]; ok {
		if s, ok := fn.(string); ok {
			fileName = s
		}
	}
	if fileName == "" {
		return mcp.NewToolResultError("missing required argument: file_name"), nil
	}
	fileContentBase64 := ""
	if fc, ok := args["file_content"]; ok {
		if s, ok := fc.(string); ok {
			fileContentBase64 = s
		}
	}
	return mcputils.ForwardUploadRequest(ctx, upstream, "POST", "/api/v2/product/license", fileName, fileContentBase64, "multipart/form-data", "InstallLicense")
}
