// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the InvalidateCache tool
const InvalidateCacheInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the InvalidateCache tool (Status: 200, Content-Type: application/json)
const InvalidateCacheResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Cache cleared successfully. Returns the number of entries that were invalidated.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **entriesInvalidated** (Type: integer, int64):\n"

// NewInvalidateCacheMCPTool creates the MCP Tool instance for InvalidateCache
func NewInvalidateCacheMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"InvalidateCache",
		"Clear the integration version cache. Use this endpoint after a new integration version is released to ensure IQ Server immediately recognizes the new version instead of waiting for cache expiration (10 minutes).\n\nPermissions required: Edit System Configuration and Users",
		[]byte(InvalidateCacheInputSchema),
	)
}

// InvalidateCacheHandler is the handler function for the InvalidateCache tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func InvalidateCacheHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/config/integrationVersions/cache", args, []string{}, contentType, "InvalidateCache")
}
