// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the MoveApplication tool
const MoveApplicationInputSchema = "{\n  \"properties\": {\n    \"applicationId\": {\n      \"description\": \"Enter the applicationId of the application to be moved.\",\n      \"type\": \"string\"\n    },\n    \"organizationId\": {\n      \"description\": \"Enter the organizationId of the destination organization.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"applicationId\",\n    \"organizationId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the MoveApplication tool (Status: 200, Content-Type: application/json)
const MoveApplicationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Application moved successfully, with/without warnings. Warnings, if any, will appear in the response body.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **errors** (Type: array):\n    - **Items** (Type: string):\n  - **warnings** (Type: array):\n    - **Items** (Type: string):\n"

// NewMoveApplicationMCPTool creates the MCP Tool instance for MoveApplication
func NewMoveApplicationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"MoveApplication",
		"Use this method to move an application from one organization to another.\n\nPermissions required: Edit IQ Elements",
		[]byte(MoveApplicationInputSchema),
	)
}

// MoveApplicationHandler is the handler function for the MoveApplication tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func MoveApplicationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/applications/{applicationId}/move/organization/{organizationId}", args, []string{"applicationId", "organizationId"}, contentType, "MoveApplication")
}
