// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PurgeUserTokens tool
const PurgeUserTokensInputSchema = "{\n  \"type\": \"object\"\n}"

// NewPurgeUserTokensMCPTool creates the MCP Tool instance for PurgeUserTokens
func NewPurgeUserTokensMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PurgeUserTokens",
		"Use this method to delete all existing LDAP user tokens.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(PurgeUserTokensInputSchema),
	)
}

// PurgeUserTokensHandler is the handler function for the PurgeUserTokens tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PurgeUserTokensHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/userTokens/purge", args, []string{}, contentType, "PurgeUserTokens")
}
