// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the RemoveProprietaryComponentNames tool
const RemoveProprietaryComponentNamesInputSchema = "{\n  \"properties\": {\n    \"format\": {\n      \"description\": \"Format for which the proprietary namespaces are being removed.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"format\"\n  ],\n  \"type\": \"object\"\n}"

// NewRemoveProprietaryComponentNamesMCPTool creates the MCP Tool instance for RemoveProprietaryComponentNames
func NewRemoveProprietaryComponentNamesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"RemoveProprietaryComponentNames",
		"Removes proprietary component namespaces for the specified format.\n\nPermissions required: Evaluate Individual Components",
		[]byte(RemoveProprietaryComponentNamesInputSchema),
	)
}

// RemoveProprietaryComponentNamesHandler is the handler function for the RemoveProprietaryComponentNames tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func RemoveProprietaryComponentNamesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/firewall/namespace_confusion/{format}", args, []string{"format"}, contentType, "RemoveProprietaryComponentNames")
}
