// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the RequestPolicyWaiver tool
const RequestPolicyWaiverInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The request JSON should contain\\u003col\\u003e\\u003cli\\u003ecomment (optional, default null) to indicate the waiver request reason\\u003c/li\\u003e\\u003cli\\u003epolicyViolationLink (link to the policy violation page in the Lifecycle UI)\\u003c/li\\u003e\\u003cli\\u003eaddWaiverLink (link to the Add Waiver page in the Lifecycle UI)\\u003c/li\\u003e\\u003c/ol\\u003e\",\n      \"properties\": {\n        \"addWaiverLink\": {\n          \"type\": \"string\"\n        },\n        \"comment\": {\n          \"type\": \"string\"\n        },\n        \"policyViolationLink\": {\n          \"type\": \"string\"\n        },\n        \"reasonId\": {\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    },\n    \"policyViolationId\": {\n      \"description\": \"Enter the policyViolationId for which you want to trigger the waiver request event.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"policyViolationId\"\n  ],\n  \"type\": \"object\"\n}"

// NewRequestPolicyWaiverMCPTool creates the MCP Tool instance for RequestPolicyWaiver
func NewRequestPolicyWaiverMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"RequestPolicyWaiver",
		"Deprecated since IQ Server 1.192. Triggers a 'Waiver Request' webhook event. Deprecated because the webhook event is now integrated into the policy waiver request process. Please use "+"\x60"+"api/v2/policyWaiverRequests{ownerType}/policyViolation/{policyViolationId}"+"\x60"+" instead. Scheduled for removal in December 2025.",
		[]byte(RequestPolicyWaiverInputSchema),
	)
}

// RequestPolicyWaiverHandler is the handler function for the RequestPolicyWaiver tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func RequestPolicyWaiverHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/policyWaivers/waiverRequests/{policyViolationId}", args, []string{"policyViolationId"}, contentType, "RequestPolicyWaiver")
}
