// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetComponentLabel tool
const SetComponentLabelInputSchema = "{\n  \"properties\": {\n    \"componentHash\": {\n      \"description\": \"Enter the SHA1 hash of the component.\",\n      \"type\": \"string\"\n    },\n    \"internalOwnerId\": {\n      \"description\": \"Possible values : applicationId or organizationId\",\n      \"type\": \"string\"\n    },\n    \"labelName\": {\n      \"description\": \"Enter the label name to assign to this component.\",\n      \"type\": \"string\"\n    },\n    \"ownerType\": {\n      \"description\": \"Possible values: application or organization\",\n      \"enum\": [\n        \"application\",\n        \"organization\"\n      ],\n      \"pattern\": \"application|organization\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"componentHash\",\n    \"internalOwnerId\",\n    \"labelName\",\n    \"ownerType\"\n  ],\n  \"type\": \"object\"\n}"

// NewSetComponentLabelMCPTool creates the MCP Tool instance for SetComponentLabel
func NewSetComponentLabelMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetComponentLabel",
		"Use this method to assign an existing label to a component.",
		[]byte(SetComponentLabelInputSchema),
	)
}

// SetComponentLabelHandler is the handler function for the SetComponentLabel tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetComponentLabelHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/v2/components/{componentHash}/labels/{labelName}/{ownerType}s/{internalOwnerId}", args, []string{"componentHash", "internalOwnerId", "labelName", "ownerType"}, contentType, "SetComponentLabel")
}
