// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetQuarantinedComponentViewAnonymousAccess tool
const SetQuarantinedComponentViewAnonymousAccessInputSchema = "{\n  \"properties\": {\n    \"enabled\": {\n      \"description\": \"Select " + "\x60" + "true" + "\x60" + " or " + "\x60" + "false" + "\x60" + " to enable or disable anonymous access.\",\n      \"type\": \"boolean\"\n    }\n  },\n  \"required\": [\n    \"enabled\"\n  ],\n  \"type\": \"object\"\n}"

// NewSetQuarantinedComponentViewAnonymousAccessMCPTool creates the MCP Tool instance for SetQuarantinedComponentViewAnonymousAccess
func NewSetQuarantinedComponentViewAnonymousAccessMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetQuarantinedComponentViewAnonymousAccess",
		"Use this method to enable/disable anonymous access to view the quarantined components.\n\nPermissions required: Edit IQ Elements",
		[]byte(SetQuarantinedComponentViewAnonymousAccessInputSchema),
	)
}

// SetQuarantinedComponentViewAnonymousAccessHandler is the handler function for the SetQuarantinedComponentViewAnonymousAccess tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetQuarantinedComponentViewAnonymousAccessHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/api/v2/firewall/quarantinedComponentView/configuration/anonymousAccess/{enabled}", args, []string{"enabled"}, contentType, "SetQuarantinedComponentViewAnonymousAccess")
}
