// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UninstallLicense tool
const UninstallLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// NewUninstallLicenseMCPTool creates the MCP Tool instance for UninstallLicense
func NewUninstallLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UninstallLicense",
		"Use this method to uninstall a product license.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(UninstallLicenseInputSchema),
	)
}

// UninstallLicenseHandler is the handler function for the UninstallLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UninstallLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/api/v2/product/license", args, []string{}, contentType, "UninstallLicense")
}
