// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonatypeiq-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateConfiguration tool
const UpdateConfigurationInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"userTokenDefaultExpirationDays\": {\n          \"format\": \"int32\",\n          \"type\": \"integer\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the UpdateConfiguration tool (Status: 200, Content-Type: application/json)
const UpdateConfigurationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Configuration updated successfully\n\n## Response Structure\n\n- Structure (Type: object):\n  - **userTokenDefaultExpirationDays** (Type: integer, int32):\n"

// NewUpdateConfigurationMCPTool creates the MCP Tool instance for UpdateConfiguration
func NewUpdateConfigurationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateConfiguration",
		"Use this method to update user token configuration. Null values are ignored (no change). Returns the current configuration after applying changes.\n\nPermissions required: Edit System Configuration and Users",
		[]byte(UpdateConfigurationInputSchema),
	)
}

// UpdateConfigurationHandler is the handler function for the UpdateConfiguration tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateConfigurationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/api/v2/config/userTokens", args, []string{}, contentType, "UpdateConfiguration")
}
