// Code generated by https://github.com/flowgent-labs/mcpfather

package pipeline

// StepKindDef defines a pipeline step kind and which StepSpec fields it uses.
// This is the single source of truth — both the validator and the schema
// generator derive their configuration from this registry.
type StepKindDef struct {
	Name     string   // "call", "jq", "foreach", "return", "emit"
	Fields   []string // StepSpec yaml-tag field names used by this kind
	Required []string // subset of Fields that are required
	DefName  string   // $def key for this kind's spec in JSON Schema
}

// StepKinds lists all supported pipeline step kinds.
// When adding a new step kind:
//  1. Add an entry here with the fields/required mapping
//  2. Add the node implementation in pkg/mcpvirtual/node/
//  3. Add the validation in validator.go validateStep()
//  4. The schema generator picks this up automatically
var StepKinds = []StepKindDef{
	{Name: "call", Fields: []string{"tool", "parse", "args"}, Required: []string{"tool", "args"}, DefName: "CallSpec"},
	{Name: "jq", Fields: []string{"from", "vars", "expr"}, Required: []string{"expr"}, DefName: "JQSpec"},
	{Name: "foreach", Fields: []string{"in", "as", "concurrency", "preserveOrder", "onMissing", "pipeline"}, Required: []string{"in", "as", "pipeline"}, DefName: "ForeachSpec"},
	{Name: "return", Fields: []string{"from", "vars", "expr"}, DefName: "ReturnSpec"},
	{Name: "emit", Fields: []string{"from", "vars", "expr"}, DefName: "EmitSpec"},
}

// ValidStepKindNames returns the names of all valid step kinds.
func ValidStepKindNames() []string {
	names := make([]string, len(StepKinds))
	for i, k := range StepKinds {
		names[i] = k.Name
	}
	return names
}

// StepKindByName returns the StepKindDef for a given kind name, or nil.
func StepKindByName(name string) *StepKindDef {
	for i := range StepKinds {
		if StepKinds[i].Name == name {
			return &StepKinds[i]
		}
	}
	return nil
}
