// Code generated by https://github.com/flowgent-labs/mcpfather

// Package mcpconfig defines the MCP server configuration types used as
// the canonical source for JSON Schema generation (via reflection). These
// types are auto-copied to generated MCP server projects.
//
// When adding new config fields or sub-structs, only this file and
// config.templ (for LoadConfig/defaultConfig logic) need updating.
// The JSON Schema is derived automatically via reflection.
package mcpconfig

// ---- top-level config ----

// Config is the root configuration for the MCP server.
type Config struct {
	Auth     AuthConfig     `yaml:"auth"`
	Tools    ToolsConfig    `yaml:"nativeTools"`
	Mgmt     MgmtConfig     `yaml:"mgmt"`
	Runtime  RuntimeConfig  `yaml:"runtime"`
	Upstream UpstreamConfig `yaml:"upstream"`
}

// ---- auth ----
//
// Naming mirrors reverse-proxy terminology (HAProxy/Envoy): "frontend" is the
// inbound side facing MCP clients (AI agents), "backend" is the outbound side
// facing upstream APIs. The two are fully decoupled.

// AuthConfig holds both frontend (inbound) and backend (outbound) auth config.
type AuthConfig struct {
	Frontend FrontendAuthConfig `yaml:"frontend"`
	Backend  BackendAuthConfig  `yaml:"backend"`
}

// FrontendAuthConfig configures inbound OAuth 2.1 bearer token validation.
type FrontendAuthConfig struct {
	OIDC FrontendOIDCConfig `yaml:"oidc"`
}

// FrontendOIDCConfig configures JWT bearer token validation against an OIDC issuer.
type FrontendOIDCConfig struct {
	Enabled                          bool     `yaml:"enabled"`
	Issuer                           string   `yaml:"issuer"`
	JWKSURI                          string   `yaml:"jwks_uri"`
	Audience                         string   `yaml:"audience"`
	EnableClientTokenClaimForward    bool     `yaml:"enable_client_token_claim_forward"`
	AdditionalClientTokenClaimForward []string `yaml:"additional_client_token_claim_forward,omitempty"`
}

// BackendAuthConfig holds authentication settings for upstream API calls.
type BackendAuthConfig struct {
	OIDC   BackendOIDCConfig `yaml:"oidc"`
	LDAP   LDAPConfig        `yaml:"ldap"`
	Static StaticAuthConfig  `yaml:"static"`
}

// BackendOIDCConfig configures machine-to-machine OIDC token exchange.
type BackendOIDCConfig struct {
	Enabled      bool   `yaml:"enabled"`
	Issuer       string `yaml:"issuer"`
	ClientID     string `yaml:"client_id"`
	ClientSecret string `yaml:"client_secret"`
	Scopes       string `yaml:"scopes"`
	GrantType    string `yaml:"grant_type"`
	TokenURL     string `yaml:"token_url"`
	Username     string `yaml:"username"`
	Password     string `yaml:"password"`
}

// LDAPConfig configures machine-to-machine LDAP service account bind auth.
type LDAPConfig struct {
	Enabled            bool   `yaml:"enabled"`
	URL                string `yaml:"url"`
	BaseDN             string `yaml:"base_dn"`
	BindDN             string `yaml:"bind_dn"`
	BindPassword       string `yaml:"bind_password"`
	InsecureSkipVerify bool   `yaml:"insecure_skip_verify"`
	Timeout            int    `yaml:"timeout"`
}

// StaticAuthConfig holds static credentials for legacy / simple upstream APIs.
type StaticAuthConfig struct {
	BearerToken     string `yaml:"bearer_token"`
	BearerTokenFile string `yaml:"bearer_token_file"`
	CookieToken     string `yaml:"cookie_token"`
	CookieTokenFile string `yaml:"cookie_token_file"`
}

// ---- tools ----

// ToolsConfig controls which native tools are exposed at startup.
type ToolsConfig struct {
	Expose *ToolsExposeConfig `yaml:"expose"`
}

// ToolsExposeConfig defines which native tools are exposed to external AI agents.
type ToolsExposeConfig struct {
	RegisterAllToolsByDefault bool     `yaml:"register_all_tools_by_default"`
	Includes                  []string `yaml:"includes"`
	Excludes                  []string `yaml:"excludes"`
}

// ---- mgmt ----

// MgmtConfig controls management endpoints (pprof, metrics, tracing).
type MgmtConfig struct {
	Enabled *bool         `yaml:"enabled"`
	Host    string        `yaml:"host"`
	Port    int           `yaml:"port"`
	Pprof   PprofConfig   `yaml:"pprof"`
	Otel    OtelConfig    `yaml:"otel"`
	Metrics MetricsConfig `yaml:"metrics"`
}

// IsEnabled returns true for mgmt unless explicitly disabled in config.
func (c MgmtConfig) IsEnabled() bool {
	if c.Enabled == nil {
		return true
	}
	return *c.Enabled
}

// PprofConfig enables Go pprof debug endpoints.
type PprofConfig struct {
	Enabled    bool   `yaml:"enabled"`
	ServerBind string `yaml:"server_bind"`
}

// OtelConfig configures the OpenTelemetry OTLP exporter.
type OtelConfig struct {
	Enabled    bool    `yaml:"enabled"`
	Endpoint   string  `yaml:"endpoint"`
	Protocol   string  `yaml:"protocol"`
	Timeout    int     `yaml:"timeout"`
	SampleRate float64 `yaml:"sample_rate"`
}

// MetricsConfig configures Prometheus metrics export.
type MetricsConfig struct {
	Enabled             *bool                `yaml:"enabled"`
	Prometheus          bool                 `yaml:"prometheus"`
	ExportInterval      string               `yaml:"export_interval"`
	HistogramBoundaries map[string][]float64 `yaml:"histogram_boundaries"`
	Labels              map[string]string    `yaml:"labels"`
}

// IsEnabled returns true for metrics unless explicitly disabled in config.
func (c MetricsConfig) IsEnabled() bool {
	if c.Enabled == nil {
		return true
	}
	return *c.Enabled
}

// ---- upstream ----

// UpstreamConfig controls how requests are forwarded to upstream APIs.
type UpstreamConfig struct {
	Endpoint                string               `yaml:"endpoint"`
	EnableMCPSessionForward bool                 `yaml:"enable_mcp_session_forward"`
	Tools                   []UpstreamToolConfig `yaml:"tools,omitempty"`
}

// UpstreamToolConfig holds per-tool upstream settings.
type UpstreamToolConfig struct {
	Name string `yaml:"name"`
}

// ---- runtime ----

// RuntimeConfig holds operational runtime settings.
type RuntimeConfig struct {
	DownloadDir      string `yaml:"download_dir"`
	LogAuthorization bool   `yaml:"log_authorization"`
}

// ---- defaults ----

// DefaultConfig returns sensible defaults used when no config file exists.
func DefaultConfig() *Config {
	t := true
	return &Config{
		Auth: AuthConfig{
			Frontend: FrontendAuthConfig{
				OIDC: FrontendOIDCConfig{
					EnableClientTokenClaimForward: true,
				},
			},
		},
		Upstream: UpstreamConfig{
			Endpoint:                "https://httpbin.org/anything",
			EnableMCPSessionForward: true,
		},
		Mgmt: MgmtConfig{
			Enabled: &t,
			Host:    "0.0.0.0",
			Port:    9991,
			Metrics: MetricsConfig{
				Enabled:        &t,
				Prometheus:     true,
				ExportInterval: "30s",
				HistogramBoundaries: map[string][]float64{
					"task": {0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120},
				},
			},
		},
	}
}
