// Code generated by https://github.com/flowgent-labs/mcpfather

package mcpconfig

import (
	"testing"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()
	if cfg == nil {
		t.Fatal("DefaultConfig returned nil")
	}
}

func TestMgmtConfig_IsEnabled(t *testing.T) {
	t.Run("nil enabled defaults to true", func(t *testing.T) {
		c := MgmtConfig{}
		if !c.IsEnabled() {
			t.Error("should be enabled by default")
		}
	})
	t.Run("explicitly enabled", func(t *testing.T) {
		enabled := true
		c := MgmtConfig{Enabled: &enabled}
		if !c.IsEnabled() {
			t.Error("should be enabled")
		}
	})
	t.Run("explicitly disabled", func(t *testing.T) {
		enabled := false
		c := MgmtConfig{Enabled: &enabled}
		if c.IsEnabled() {
			t.Error("should be disabled")
		}
	})
}

func TestMetricsConfig_IsEnabled(t *testing.T) {
	t.Run("nil enabled defaults to true", func(t *testing.T) {
		c := MetricsConfig{}
		if !c.IsEnabled() {
			t.Error("should be enabled by default")
		}
	})
	t.Run("explicitly enabled", func(t *testing.T) {
		enabled := true
		c := MetricsConfig{Enabled: &enabled}
		if !c.IsEnabled() {
			t.Error("should be enabled")
		}
	})
	t.Run("explicitly disabled", func(t *testing.T) {
		enabled := false
		c := MetricsConfig{Enabled: &enabled}
		if c.IsEnabled() {
			t.Error("should be disabled")
		}
	})
}
