// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"context"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/go-ldap/ldap/v3"
)

// ---- OIDC token manager ----

// oidcToken holds a cached OIDC access token with its expiry.
type oidcToken struct {
	AccessToken string
	ExpiresAt   time.Time
}

// oidcManager handles OIDC client credentials flow with auto-refresh.
type oidcManager struct {
	cfg        BackendOIDCConfig
	httpClient *http.Client
	token      *oidcToken
	mu         sync.Mutex
	stopCh     chan struct{}
	doneCh     chan struct{}
}

var (
	oidcOnce     sync.Once
	oidcInstance *oidcManager
)

// InitOIDC starts the OIDC token manager. Safe to call multiple times; only the
// first call has effect. When OIDC is disabled in config, this is a no-op.
func InitOIDC(cfg BackendOIDCConfig) {
	oidcOnce.Do(func() {
		if !cfg.Enabled {
			return
		}
		om := &oidcManager{
			cfg: cfg,
			httpClient: &http.Client{
				Timeout: 15 * time.Second,
			},
			stopCh: make(chan struct{}),
			doneCh: make(chan struct{}),
		}
		if err := om.refresh(context.Background()); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: initial OIDC token fetch failed: %v\n", err)
		}
		oidcInstance = om
		go om.refreshLoop()
	})
}

// GetOIDCToken returns the current valid OIDC access token, refreshing if needed.
// Returns empty string if OIDC is not configured or the token fetch failed.
func GetOIDCToken() string {
	if oidcInstance == nil {
		return ""
	}
	return oidcInstance.getToken()
}

// ShutdownOIDC stops the background refresh loop. Call during server shutdown.
func ShutdownOIDC() {
	if oidcInstance == nil {
		return
	}
	close(oidcInstance.stopCh)
	<-oidcInstance.doneCh
}

func (m *oidcManager) getToken() string {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.token != nil && time.Now().Add(30*time.Second).Before(m.token.ExpiresAt) {
		return m.token.AccessToken
	}
	// Synchronous refresh when token is expired or about to expire
	if err := m.refreshLocked(context.Background()); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: OIDC token refresh failed: %v\n", err)
	}
	if m.token != nil {
		return m.token.AccessToken
	}
	return ""
}

func (m *oidcManager) refresh(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.refreshLocked(ctx)
}

func (m *oidcManager) refreshLocked(ctx context.Context) error {
	tokenURL, err := m.resolveTokenURL(ctx)
	if err != nil {
		return fmt.Errorf("resolve token endpoint: %w", err)
	}

	grantType := m.cfg.GrantType
	if grantType == "" {
		grantType = "client_credentials"
	}
	data := url.Values{
		"grant_type":    {grantType},
		"client_id":     {m.cfg.ClientID},
		"client_secret": {m.cfg.ClientSecret},
	}
	if grantType == "password" {
		data.Set("username", m.cfg.Username)
		data.Set("password", m.cfg.Password)
	}
	if m.cfg.Scopes != "" {
		data.Set("scope", m.cfg.Scopes)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, tokenURL, strings.NewReader(data.Encode()))
	if err != nil {
		return fmt.Errorf("create token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := m.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("token request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read token response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("token endpoint returned %d: %s", resp.StatusCode, string(body))
	}

	var tr tokenResponse
	if err := json.Unmarshal(body, &tr); err != nil {
		return fmt.Errorf("parse token response: %w", err)
	}
	if tr.AccessToken == "" {
		return fmt.Errorf("token response missing access_token")
	}

	expiresIn := tr.ExpiresIn
	if expiresIn <= 0 {
		expiresIn = 3600
	}

	m.token = &oidcToken{
		AccessToken: tr.AccessToken,
		ExpiresAt:   time.Now().Add(time.Duration(expiresIn) * time.Second),
	}
	return nil
}

func (m *oidcManager) resolveTokenURL(ctx context.Context) (string, error) {
	if m.cfg.TokenURL != "" {
		return m.cfg.TokenURL, nil
	}
	issuer := strings.TrimSuffix(m.cfg.Issuer, "/")
	discoveryURL := issuer + "/.well-known/openid-configuration"

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, discoveryURL, nil)
	if err != nil {
		return "", fmt.Errorf("create discovery request: %w", err)
	}

	resp, err := m.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("discovery request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("discovery returned %d", resp.StatusCode)
	}

	var disc oidcDiscovery
	if err := json.NewDecoder(resp.Body).Decode(&disc); err != nil {
		return "", fmt.Errorf("parse discovery: %w", err)
	}
	if disc.TokenEndpoint == "" {
		return "", fmt.Errorf("discovery missing token_endpoint")
	}
	return disc.TokenEndpoint, nil
}

func (m *oidcManager) refreshLoop() {
	defer close(m.doneCh)

	// Refresh at half the TTL, or every 30 minutes as a fallback
	ticker := time.NewTicker(30 * time.Minute)
	defer ticker.Stop()

	for {
		select {
		case <-m.stopCh:
			return
		case <-ticker.C:
			if m.token == nil || time.Now().Add(5*time.Minute).After(m.token.ExpiresAt) {
				if err := m.refresh(context.Background()); err != nil {
					fmt.Fprintf(os.Stderr, "Warning: background OIDC refresh failed: %v\n", err)
				}
			}
		}
	}
}

type tokenResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

type oidcDiscovery struct {
	TokenEndpoint string `json:"token_endpoint"`
}

// ---- LDAP token manager ----

// ldapToken holds a cached Basic auth token generated from an LDAP bind.
type ldapToken struct {
	BasicAuth string    // "Basic base64(bindDN:bindPassword)"
	ExpiresAt time.Time // token refresh time
}

// ldapManager handles LDAP service account bind with auto-refresh.
type ldapManager struct {
	cfg    LDAPConfig
	token  *ldapToken
	mu     sync.Mutex
	stopCh chan struct{}
	doneCh chan struct{}
}

var (
	ldapOnce     sync.Once
	ldapInstance *ldapManager
)

// InitLDAP starts the LDAP token manager. Safe to call multiple times; only the
// first call has effect. When LDAP is disabled in config, this is a no-op.
func InitLDAP(cfg LDAPConfig) {
	ldapOnce.Do(func() {
		if !cfg.Enabled {
			return
		}
		lm := &ldapManager{
			cfg:    cfg,
			stopCh: make(chan struct{}),
			doneCh: make(chan struct{}),
		}
		if err := lm.refresh(context.Background()); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: initial LDAP bind failed: %v\n", err)
		}
		ldapInstance = lm
		go lm.refreshLoop()
	})
}

// GetLDAPToken returns the current LDAP Basic auth token. Returns empty string
// if LDAP is not configured or the bind failed.
func GetLDAPToken() string {
	if ldapInstance == nil {
		return ""
	}
	return ldapInstance.getToken()
}

// ShutdownLDAP stops the background refresh loop.
func ShutdownLDAP() {
	if ldapInstance == nil {
		return
	}
	close(ldapInstance.stopCh)
	<-ldapInstance.doneCh
}

func (m *ldapManager) getToken() string {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.token != nil && time.Now().Add(30*time.Second).Before(m.token.ExpiresAt) {
		return m.token.BasicAuth
	}
	if err := m.refreshLocked(context.Background()); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: LDAP bind refresh failed: %v\n", err)
	}
	if m.token != nil {
		return m.token.BasicAuth
	}
	return ""
}

func (m *ldapManager) refresh(ctx context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.refreshLocked(ctx)
}

func (m *ldapManager) refreshLocked(_ context.Context) error {
	// Dial LDAP server
	var conn *ldap.Conn
	var err error

	if m.cfg.InsecureSkipVerify {
		conn, err = ldap.DialURL(m.cfg.URL, ldap.DialWithTLSConfig(&tls.Config{
			InsecureSkipVerify: true,
		}))
	} else {
		conn, err = ldap.DialURL(m.cfg.URL)
	}
	if err != nil {
		return fmt.Errorf("dial LDAP %s: %w", m.cfg.URL, err)
	}
	defer conn.Close()

	// Set timeout
	timeout := time.Duration(m.cfg.Timeout) * time.Second
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	conn.SetTimeout(timeout)

	// Bind with service account
	if err := conn.Bind(m.cfg.BindDN, m.cfg.BindPassword); err != nil {
		return fmt.Errorf("LDAP bind as %s: %w", m.cfg.BindDN, err)
	}

	// Build Basic auth header from bind credentials
	auth := base64.StdEncoding.EncodeToString([]byte(m.cfg.BindDN + ":" + m.cfg.BindPassword))

	// Default TTL 30 minutes; user can adjust via the background loop
	ttl := 30 * time.Minute
	m.token = &ldapToken{
		BasicAuth: "Basic " + auth,
		ExpiresAt: time.Now().Add(ttl),
	}
	return nil
}

func (m *ldapManager) refreshLoop() {
	defer close(m.doneCh)

	// Refresh every 25 minutes (5 minutes before the 30-minute default TTL)
	ticker := time.NewTicker(25 * time.Minute)
	defer ticker.Stop()

	for {
		select {
		case <-m.stopCh:
			return
		case <-ticker.C:
			if m.token == nil || time.Now().Add(5*time.Minute).After(m.token.ExpiresAt) {
				if err := m.refresh(context.Background()); err != nil {
					fmt.Fprintf(os.Stderr, "Warning: background LDAP refresh failed: %v\n", err)
				}
			}
		}
	}
}
