// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
)

type contextKey string

const HTTPHeadersContextKey contextKey = "mcp-http-headers"

// WithHTTPHeaders stores HTTP headers in the context for forwarding to upstream.
func WithHTTPHeaders(ctx context.Context, headers http.Header) context.Context {
	return context.WithValue(ctx, HTTPHeadersContextKey, headers)
}

// GetHTTPHeaders retrieves HTTP headers from the context.
func GetHTTPHeaders(ctx context.Context) http.Header {
	if h, ok := ctx.Value(HTTPHeadersContextKey).(http.Header); ok {
		return h
	}
	return nil
}

// ForwardRequest sends an HTTP request to the upstream endpoint and returns the response.
// All HTTP headers stored in ctx are forwarded to the upstream service.
func ForwardRequest(ctx context.Context, upstreamBase string, method string, path string, args map[string]interface{}, pathKeys []string, contentType string) (*http.Response, error) {
	// Build URL
	upstreamURL := strings.TrimSuffix(upstreamBase, "/") + path

	// Replace path parameters and collect query parameters
	query := url.Values{}
	for key, val := range args {
		// "body" is reserved for request body, never goes in query
		if key == "body" {
			continue
		}
		placeholder := "{" + key + "}"
		if strings.Contains(upstreamURL, placeholder) {
			upstreamURL = strings.ReplaceAll(upstreamURL, placeholder, valueToString(val))
		} else {
			if strVal, ok := val.(string); ok {
				query.Set(key, strVal)
			} else {
				query.Set(key, valueToString(val))
			}
		}
	}
	if len(query) > 0 {
		upstreamURL += "?" + query.Encode()
	}

	// Build request body
	var bodyReader io.Reader
	var bodyBytes []byte
	var err error
	if method != "GET" && method != "HEAD" {
		var bodyData interface{}
		if bodyArg, ok := args["body"]; ok {
			bodyData = bodyArg
		} else {
			bodyData = buildJSONBody(args, pathKeys)
		}
		bodyBytes, err = marshalJSONNoSci(bodyData)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = strings.NewReader(string(bodyBytes))
	}

	req, err := http.NewRequestWithContext(ctx, method, upstreamURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("failed to create upstream request: %w", err)
	}

	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}

	// Forward all headers from context (skip hop-by-hop and MCP-specific)
	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" || lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" || lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" || lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" || lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}

	// The client's own Authorization header is deliberately excluded above
	// (see "authorization" in the skip list) and never falls through here.
	// Per the MCP Authorization spec's Token Passthrough Prohibition, a
	// token issued for this MCP server (validated by the frontend resource
	// server layer, see resource_server.go) MUST NOT be forwarded as-is to
	// upstream APIs it was never issued for. The server always uses its own
	// backend credential instead.
	if token := GetUpstreamToken(); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}

	// Attach upstream cookie from config (for session-based auth like JSESSIONID)
	if cookie := GetUpstreamCookie(); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}

	// Forward MCP session ID when enable_mcp_session_forward is configured.
	if cfg := GetConfig(); cfg != nil && cfg.Upstream.EnableMCPSessionForward {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}

	// Forward validated client token claims when enable_client_token_claim_forward
	// is configured (default: true). These are extracted from the frontend JWT
	// by the resource server layer — never from the inbound Authorization header.
	if cfg := GetConfig(); cfg != nil && cfg.Auth.Frontend.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Auth.Frontend.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	// Log outgoing request with final headers
	LogRequest(method, upstreamURL, query, req.Header, bodyBytes)

	// Inject W3C trace context for distributed tracing
	InjectTraceContext(ctx, req.Header)

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	return client.Do(req)
}

// FormatAuthorizationHeader normalizes a token for use in an HTTP Authorization header.
// If the token already has a recognized prefix (Bearer or Basic, case-insensitive),
// it is returned unchanged. Otherwise, "Bearer " is prepended.
func FormatAuthorizationHeader(token string) string {
	token = strings.TrimSpace(token)
	if token == "" {
		return token
	}
	lower := strings.ToLower(token)
	if strings.HasPrefix(lower, "bearer ") || strings.HasPrefix(lower, "basic ") {
		return token
	}
	return "Bearer " + token
}

// valueToString converts an interface{} to a string suitable for URLs and
// query parameters. It handles float64 values (from JSON unmarshalling)
// without scientific notation, which would break integer path parameters.
func valueToString(val interface{}) string {
	switch v := val.(type) {
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(v), 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", val)
	}
}

// buildJSONBody creates a map of args that should be included in the JSON body
// (i.e., args that are not path params or query params).
func buildJSONBody(args map[string]interface{}, pathAndQueryKeys []string) map[string]interface{} {
	skip := make(map[string]bool, len(pathAndQueryKeys))
	for _, k := range pathAndQueryKeys {
		skip[k] = true
	}
	body := make(map[string]interface{}, len(args))
	for k, v := range args {
		if !skip[k] {
			body[k] = v
		}
	}
	return body
}

// ParamsParser provides a generic way to parse MCP tool arguments into typed structs.
func ParamsParser[T any](args map[string]interface{}) (*T, error) {
	jsonData, err := marshalJSONNoSci(args)
	if err != nil {
		return nil, fmt.Errorf("failed to process arguments: %w", err)
	}

	var typedArgs T
	if err := json.Unmarshal(jsonData, &typedArgs); err != nil {
		return nil, fmt.Errorf("invalid argument structure: %w", err)
	}

	return &typedArgs, nil
}

// HeaderizeClaim converts a snake_case claim name to an HTTP header suffix.
// e.g. "given_name" → "Given-Name", "preferred_username" → "Preferred-Username".
func HeaderizeClaim(claim string) string {
	parts := strings.Split(claim, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "-")
}

// marshalJSONNoSci marshals data to JSON without scientific notation for
// floating point / integer values (which may come from JSON
// unmarshalling as float64). It recursively sanitises maps and slices.
func marshalJSONNoSci(v interface{}) ([]byte, error) {
	return json.Marshal(sanitizeForJSON(v))
}

// sanitizeForJSON recursively replaces float64/float32 values with
// json.RawMessage containing the decimal representation of the number.
// This prevents json.Marshal from emitting scientific notation.
func sanitizeForJSON(v interface{}) interface{} {
	switch val := v.(type) {
	case float64:
		return json.RawMessage(strconv.FormatFloat(val, 'f', -1, 64))
	case float32:
		return json.RawMessage(strconv.FormatFloat(float64(val), 'f', -1, 32))
	case []interface{}:
		out := make([]interface{}, len(val))
		for i, item := range val {
			out[i] = sanitizeForJSON(item)
		}
		return out
	case map[string]interface{}:
		out := make(map[string]interface{}, len(val))
		for k, item := range val {
			out[k] = sanitizeForJSON(item)
		}
		return out
	}
	return v
}

// IsBinaryContentType checks whether a Content-Type indicates binary data.
// The logic is inverted: instead of maintaining a whitelist of binary types,
// we define what is TEXT and treat everything else as binary.
func IsBinaryContentType(ct string) bool {
	ct = strings.TrimSpace(strings.ToLower(ct))
	mediaType, _, _ := mime.ParseMediaType(ct)
	if mediaType == "" {
		return true // unknown content-type, treat as binary to be safe
	}

	if strings.HasPrefix(mediaType, "text/") {
		return false
	}
	switch mediaType {
	case "application/json",
		"application/javascript",
		"application/x-www-form-urlencoded",
		"application/xml",
		"application/atom+xml",
		"application/rss+xml",
		"application/soap+xml":
		return false
	}
	if strings.HasSuffix(mediaType, "+json") ||
		strings.HasSuffix(mediaType, "+xml") {
		return false
	}

	return true
}

// IsBinaryDownload checks whether an HTTP response represents a binary file download.
func IsBinaryDownload(resp *http.Response) bool {
	if resp.Header.Get("Content-Disposition") != "" {
		return true
	}
	return IsBinaryContentType(resp.Header.Get("Content-Type"))
}

// DetermineFileName extracts a filename from the HTTP response, falling back to a
// default name with an extension derived from the response Content-Type.
func DetermineFileName(resp *http.Response, defaultName string) string {
	if cd := resp.Header.Get("Content-Disposition"); cd != "" {
		if _, params, err := mime.ParseMediaType(cd); err == nil {
			if fn := params["filename"]; fn != "" {
				return filepath.Clean(fn)
			}
		}
	}
	if u, err := url.Parse(resp.Request.URL.String()); err == nil {
		if segs := strings.Split(strings.Trim(u.Path, "/"), "/"); len(segs) > 0 {
			if name, _ := url.QueryUnescape(segs[len(segs)-1]); name != "" {
				return filepath.Clean(name)
			}
		}
	}
	ct := resp.Header.Get("Content-Type")
	ext := ""
	if ct != "" {
		mediaType, _, _ := mime.ParseMediaType(ct)
		ext = mime.TypeByExtension(mediaType)
		if ext == "" {
			switch {
			case strings.HasPrefix(mediaType, "image/"):
				ext = ".png"
			case strings.HasPrefix(mediaType, "video/"):
				ext = ".mp4"
			case strings.HasPrefix(mediaType, "audio/"):
				ext = ".mp3"
			case mediaType == "application/pdf":
				ext = ".pdf"
			case mediaType == "application/octet-stream":
				ext = ".bin"
			case mediaType == "application/zip":
				ext = ".zip"
			default:
				ext = ".dat"
			}
		}
	}
	return defaultName + ext
}

// SaveBinaryStream streams the response body directly to a file in the downloads
// directory without buffering the entire content in memory. Returns the file path
// and the number of bytes written.
func SaveBinaryStream(resp *http.Response, defaultName string) (string, int64, error) {
	fileName := DetermineFileName(resp, defaultName)
	downloadDir, err := resolveDownloadDir()
	if err != nil {
		return "", 0, err
	}
	if err := os.MkdirAll(downloadDir, 0755); err != nil {
		return "", 0, fmt.Errorf("failed to create download directory %s: %w", downloadDir, err)
	}
	filePath := filepath.Join(downloadDir, fileName)
	f, err := os.Create(filePath)
	if err != nil {
		return "", 0, fmt.Errorf("failed to create file %s: %w", filePath, err)
	}
	defer f.Close()
	written, err := io.Copy(f, resp.Body)
	if err != nil {
		return "", 0, fmt.Errorf("failed to stream response to file %s: %w", filePath, err)
	}
	return filePath, written, nil
}

// ForwardAndParseResponse sends a request to the upstream and handles the full
// response lifecycle: error status codes, binary downloads, and text responses.
// All non-upload tool handlers call this to eliminate per-tool boilerplate.
func ForwardAndParseResponse(ctx context.Context, upstreamBase, method, path string, args map[string]interface{}, pathKeys []string, contentType, toolName string) (*mcp.CallToolResult, error) {
	startTime := time.Now()
	resp, err := ForwardRequest(ctx, upstreamBase, method, path, args, pathKeys, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if IsBinaryDownload(resp) {
		filePath, written, err := SaveBinaryStream(resp, toolName)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, body)

	return mcp.NewToolResultText(string(body)), nil
}

// ForwardUploadRequest reads file data (from uploads directory or base64 content)
// and sends it as the request body to the upstream service.
//
// Two modes:
//   - fileContentBase64 != "": decode and stage in uploads dir, then upload
//     (supports HTTP mode where clients send file content inline).
//   - fileContentBase64 == "": read fileName from the uploads directory
//     (supports stdio mode where files are placed on the shared filesystem).
func ForwardUploadRequest(ctx context.Context, upstreamBase, method, path, fileName, fileContentBase64, contentType, toolName string) (*mcp.CallToolResult, error) {
	var fileData []byte

	if fileContentBase64 != "" {
		decoded, err := base64.StdEncoding.DecodeString(fileContentBase64)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("failed to decode base64 file content: %v", err)), nil
		}
		uploadDir, err := resolveUploadDir()
		if err != nil {
			return nil, fmt.Errorf("failed to resolve upload dir: %w", err)
		}
		if err := os.MkdirAll(uploadDir, 0755); err != nil {
			return nil, fmt.Errorf("failed to create upload directory %s: %w", uploadDir, err)
		}
		stagedPath := filepath.Join(uploadDir, filepath.Clean(fileName))
		if err := os.WriteFile(stagedPath, decoded, 0644); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("failed to stage uploaded file %s: %v", stagedPath, err)), nil
		}
		fileData = decoded
	} else {
		uploadDir, err := resolveUploadDir()
		if err != nil {
			return nil, fmt.Errorf("failed to resolve upload dir: %w", err)
		}
		localPath := filepath.Join(uploadDir, filepath.Clean(fileName))
		data, err := os.ReadFile(localPath)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("failed to read file %s from uploads directory: %v", localPath, err)), nil
		}
		fileData = data
	}

	startTime := time.Now()
	upstreamURL := strings.TrimSuffix(upstreamBase, "/") + path

	req, err := http.NewRequestWithContext(ctx, method, upstreamURL, bytes.NewReader(fileData))
	if err != nil {
		return nil, fmt.Errorf("failed to create upstream request: %w", err)
	}
	req.Header.Set("Content-Type", contentType)

	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" || lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" || lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" || lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" || lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}
	if token := GetUpstreamToken(); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}

	if cookie := GetUpstreamCookie(); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}

	if cfg := GetConfig(); cfg != nil && cfg.Upstream.EnableMCPSessionForward {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}

	if cfg := GetConfig(); cfg != nil && cfg.Auth.Frontend.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Auth.Frontend.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	LogRequest(method, upstreamURL, nil, req.Header, fileData)

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if IsBinaryDownload(resp) {
		filePath, written, err := SaveBinaryStream(resp, toolName)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, body)

	return mcp.NewToolResultText(string(body)), nil
}
