// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestFormatAuthorizationHeader(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"empty", "", ""},
		{"bare token", "abc123", "Bearer abc123"},
		{"already bearer", "Bearer abc123", "Bearer abc123"},
		{"already basic", "Basic dXNlcjpwYXNz", "Basic dXNlcjpwYXNz"},
		{"lower bearer", "bearer abc123", "bearer abc123"},
		{"trim spaces", "  abc123  ", "Bearer abc123"},
		{"basic lower", "basic dXNlcjpwYXNz", "basic dXNlcjpwYXNz"},
		{"all uppercase", "BEARER xyz", "BEARER xyz"},
		{"token with spaces inside", "  token with spaces  ", "Bearer token with spaces"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := FormatAuthorizationHeader(tt.input)
			if got != tt.want {
				t.Errorf("FormatAuthorizationHeader(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestValueToString(t *testing.T) {
	tests := []struct {
		name  string
		input interface{}
		want  string
	}{
		{"string", "hello", "hello"},
		{"int", 42, "42"},
		{"float64 no sci", float64(123), "123"},
		{"float64 large", float64(1e9), "1000000000"},
		{"float32", float32(3.14), "3.14"},
		{"bool", true, "true"},
		{"nil", nil, "<nil>"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := valueToString(tt.input)
			if got != tt.want {
				t.Errorf("valueToString(%v) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestBuildJSONBody(t *testing.T) {
	args := map[string]interface{}{
		"body":  "should be in body",
		"name":  "test",
		"age":   42,
		"debug": true,
	}
	pathKeys := []string{"name"}
	result := buildJSONBody(args, pathKeys)
	if _, ok := result["name"]; ok {
		t.Error("path key 'name' should be excluded from body")
	}
	if _, ok := result["body"]; !ok {
		t.Error("body key should be in body")
	}
	if v, ok := result["age"]; !ok || v != 42 {
		t.Errorf("age should be 42, got %v", v)
	}
}

func TestHeaderizeClaim(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"given_name", "Given-Name"},
		{"preferred_username", "Preferred-Username"},
		{"email", "Email"},
		{"family_name", "Family-Name"},
		{"", ""},
		{"single", "Single"},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := HeaderizeClaim(tt.input)
			if got != tt.want {
				t.Errorf("HeaderizeClaim(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestSanitizeForJSON(t *testing.T) {
	t.Run("float64 no sci", func(t *testing.T) {
		result := sanitizeForJSON(1e10)
		if stringResult, ok := result.([]byte); ok {
			if string(stringResult) != "10000000000" {
				t.Errorf("got %q, want %q", string(stringResult), "10000000000")
			}
		}
	})
	t.Run("nested map", func(t *testing.T) {
		result := sanitizeForJSON(map[string]interface{}{"count": float64(100)})
		m := result.(map[string]interface{})
		if m == nil {
			t.Error("map should not be nil")
		}
	})
	t.Run("simple string passthrough", func(t *testing.T) {
		result := sanitizeForJSON("hello")
		if result.(string) != "hello" {
			t.Error("string should pass through")
		}
	})
}

func TestMarshalJSONNoSci(t *testing.T) {
	data := map[string]interface{}{"id": float64(1000000000000000)}
	result, err := marshalJSONNoSci(data)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(string(result), "e+") {
		t.Errorf("scientific notation found: %s", string(result))
	}
}

func TestIsBinaryContentType(t *testing.T) {
	tests := []struct {
		ct   string
		want bool
	}{
		{"text/html", false},
		{"application/json", false},
		{"application/xml", false},
		{"application/soap+xml", false},
		{"application/problem+json", false},
		{"application/octet-stream", true},
		{"image/png", true},
		{"video/mp4", true},
		{"application/pdf", true},
		{"", true},
		{"application/zip", true},
		{"application/javascript", false},
		{"application/atom+xml", false},
		{"application/rss+xml", false},
		{"application/x-www-form-urlencoded", false},
	}
	for _, tt := range tests {
		t.Run(tt.ct, func(t *testing.T) {
			if got := IsBinaryContentType(tt.ct); got != tt.want {
				t.Errorf("IsBinaryContentType(%q) = %v, want %v", tt.ct, got, tt.want)
			}
		})
	}
}

func TestIsBinaryDownload(t *testing.T) {
	t.Run("with content-disposition", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Disposition": {"attachment; filename=report.pdf"}}}
		if !IsBinaryDownload(resp) {
			t.Error("should be binary download")
		}
	})
	t.Run("binary content type", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Type": {"application/octet-stream"}}}
		if !IsBinaryDownload(resp) {
			t.Error("should be binary download")
		}
	})
	t.Run("json is not binary", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Type": {"application/json"}}}
		if IsBinaryDownload(resp) {
			t.Error("JSON should not be binary")
		}
	})
}

func TestDetermineFileName(t *testing.T) {
	t.Run("from content-disposition", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Disposition", `attachment; filename="report.pdf"`)
		resp.Request, _ = http.NewRequest("GET", ts.URL+"/api/download", nil)
		got := DetermineFileName(resp, "default")
		if got != "report.pdf" {
			t.Errorf("got %q, want %q", got, "report.pdf")
		}
		resp.Body.Close()
	})
	t.Run("from URL path", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL + "/downloads/data.csv")
		resp.Header.Set("Content-Type", "text/csv")
		resp.Request, _ = http.NewRequest("GET", ts.URL+"/downloads/data.csv", nil)
		got := DetermineFileName(resp, "default")
		if got != "data.csv" {
			t.Errorf("got %q, want %q", got, "data.csv")
		}
		resp.Body.Close()
	})
	t.Run("fallback with content-type extension", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "application/pdf")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "output")
		if got != "output.pdf" {
			t.Errorf("got %q, want %q", got, "output.pdf")
		}
		resp.Body.Close()
	})
	t.Run("unknown content type fallback", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "application/octet-stream")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "download")
		if got != "download.bin" {
			t.Errorf("got %q, want %q", got, "download.bin")
		}
		resp.Body.Close()
	})
	t.Run("video content type", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "video/mp4")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "clip")
		if got != "clip.mp4" {
			t.Errorf("got %q, want %q", got, "clip.mp4")
		}
		resp.Body.Close()
	})
}

func TestParamsParser(t *testing.T) {
	type testArgs struct {
		Name  string `json:"name"`
		Count int    `json:"count"`
	}
	args := map[string]interface{}{
		"name":  "test",
		"count": float64(5),
	}
	result, err := ParamsParser[testArgs](args)
	if err != nil {
		t.Fatalf("ParamsParser failed: %v", err)
	}
	if result.Name != "test" {
		t.Errorf("name: got %q, want %q", result.Name, "test")
	}
	if result.Count != 5 {
		t.Errorf("count: got %d, want %d", result.Count, 5)
	}
}

func TestForwardRequest_WithMockUpstream(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "GET" && r.URL.Path == "/api/test" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"status":"ok"}`))
			return
		}
		if r.Method == "POST" && r.URL.Path == "/api/create" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusCreated)
			w.Write([]byte(`{"id":1}`))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer ts.Close()

	t.Setenv("MCP__UPSTREAM__ENDPOINT", ts.URL)
	LoadConfig("sonatypeiq-mcp")

	t.Run("GET request", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Errorf("expected 200, got %d", resp.StatusCode)
		}
	})

	t.Run("POST with body", func(t *testing.T) {
		ctx := context.Background()
		args := map[string]interface{}{"body": map[string]interface{}{"name": "test"}}
		resp, err := ForwardRequest(ctx, ts.URL, "POST", "/api/create", args, []string{}, "application/json")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusCreated {
			t.Errorf("expected 201, got %d", resp.StatusCode)
		}
	})

	t.Run("path parameter substitution", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/item/{id}", map[string]interface{}{"id": "42"}, []string{"id"}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})

	t.Run("query parameters", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/search", map[string]interface{}{"q": "test", "page": float64(1)}, []string{}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})

	t.Run("POST auto body", func(t *testing.T) {
		ctx := context.Background()
		args := map[string]interface{}{"name": "test", "age": float64(30)}
		resp, err := ForwardRequest(ctx, ts.URL, "POST", "/api/create", args, []string{"name"}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})
}

func TestForwardAndParseResponse(t *testing.T) {
	t.Run("success", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
		if result.IsError {
			t.Error("unexpected error result")
		}
	})

	t.Run("upstream error 500", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusInternalServerError)
			w.Write([]byte(`{"error":"boom"}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !result.IsError {
			t.Error("expected error result")
		}
	})

	t.Run("upstream error 404", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
			w.Write([]byte(`{"error":"not found"}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !result.IsError {
			t.Error("expected error result for 404")
		}
	})
}

func TestWithHTTPHeaders(t *testing.T) {
	headers := http.Header{"X-Custom": {"custom-value"}}
	ctx := WithHTTPHeaders(context.Background(), headers)
	got := GetHTTPHeaders(ctx)
	if got == nil {
		t.Fatal("GetHTTPHeaders returned nil")
	}
	if got.Get("X-Custom") != "custom-value" {
		t.Errorf("expected custom-value, got %q", got.Get("X-Custom"))
	}
}

func TestGetHTTPHeaders_Nil(t *testing.T) {
	got := GetHTTPHeaders(context.Background())
	if got != nil {
		t.Error("expected nil for context without headers")
	}
}

func TestForwardUploadRequest(t *testing.T) {
	t.Run("base64 mode", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			body, _ := io.ReadAll(r.Body)
			if !bytes.Equal(body, []byte("test content")) {
				t.Errorf("unexpected body: %s", string(body))
			}
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		tmpDir := t.TempDir()
		oldCfg := GetConfig()
		t.Setenv("MCP__RUNTIME__DOWNLOAD_DIR", tmpDir)
		LoadConfig("sonatypeiq-mcp")
		defer SetConfig(oldCfg)

		content := "dGVzdCBjb250ZW50" // base64 of "test content"
		result, err := ForwardUploadRequest(context.Background(), ts.URL, "PUT", "/api/upload", "test.txt", content, "text/plain", "TestUpload")
		if err != nil {
			t.Fatalf("ForwardUploadRequest failed: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
	})

	t.Run("invalid base64", func(t *testing.T) {
		result, err := ForwardUploadRequest(context.Background(), "http://example.com", "PUT", "/api/upload", "test.txt", "!!!bad-base64!!!", "text/plain", "TestUpload")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !result.IsError {
			t.Error("expected error for invalid base64")
		}
	})
}
