// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"os"
	"path/filepath"
	"testing"

	"sonatypeiq-mcp/pkg/mcpconfig"
)

func TestSetGetConfig(t *testing.T) {
	cfg := &Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: "https://test.example.com"}}
	SetConfig(cfg)

	got := GetConfig()
	if got == nil {
		t.Fatal("GetConfig returned nil")
	}
	if got.Upstream.Endpoint != "https://test.example.com" {
		t.Errorf("endpoint: got %q, want %q", got.Upstream.Endpoint, "https://test.example.com")
	}

	t.Run("nil config", func(t *testing.T) {
		SetConfig(nil)
		if GetConfig() != nil {
			t.Error("GetConfig should return nil after SetConfig(nil)")
		}
	})
}

func TestGetUpstreamEndpoint(t *testing.T) {
	t.Run("configured", func(t *testing.T) {
		SetConfig(&Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: "https://custom.example.com"}})
		got := GetUpstreamEndpoint()
		if got != "https://custom.example.com" {
			t.Errorf("got %q", got)
		}
	})
	t.Run("default when nil config", func(t *testing.T) {
		SetConfig(nil)
		got := GetUpstreamEndpoint()
		if got != "https://httpbin.org/anything" {
			t.Errorf("got %q, want default", got)
		}
	})
	t.Run("default when empty endpoint", func(t *testing.T) {
		SetConfig(&Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: ""}})
		got := GetUpstreamEndpoint()
		if got != "https://httpbin.org/anything" {
			t.Errorf("got %q, want default", got)
		}
	})
}

func TestIsDefaultUpstreamEndpoint(t *testing.T) {
	t.Run("nil config", func(t *testing.T) {
		SetConfig(nil)
		if !IsDefaultUpstreamEndpoint() {
			t.Error("should be default")
		}
	})
	t.Run("empty endpoint", func(t *testing.T) {
		SetConfig(&Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: ""}})
		if !IsDefaultUpstreamEndpoint() {
			t.Error("should be default")
		}
	})
	t.Run("explicit default value", func(t *testing.T) {
		SetConfig(&Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: "https://httpbin.org/anything"}})
		if !IsDefaultUpstreamEndpoint() {
			t.Error("explicit default endpoint should still be default")
		}
	})
	t.Run("custom endpoint", func(t *testing.T) {
		SetConfig(&Config{Upstream: mcpconfig.UpstreamConfig{Endpoint: "https://custom.example.com"}})
		if IsDefaultUpstreamEndpoint() {
			t.Error("should not be default")
		}
	})
}

func TestGetUpstreamToken(t *testing.T) {
	t.Run("static bearer token", func(t *testing.T) {
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{BearerToken: "test-token"},
			},
		}})
		got := GetUpstreamToken()
		if got != "test-token" {
			t.Errorf("got %q, want %q", got, "test-token")
		}
	})
	t.Run("static bearer token file", func(t *testing.T) {
		tmpFile := filepath.Join(t.TempDir(), "token")
		os.WriteFile(tmpFile, []byte("file-token"), 0644)
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{BearerTokenFile: tmpFile},
			},
		}})
		got := GetUpstreamToken()
		if got != "file-token" {
			t.Errorf("got %q, want %q", got, "file-token")
		}
	})
	t.Run("token file with whitespace trimming", func(t *testing.T) {
		tmpFile := filepath.Join(t.TempDir(), "tok2")
		os.WriteFile(tmpFile, []byte("  padded-token  \n"), 0644)
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{BearerTokenFile: tmpFile},
			},
		}})
		got := GetUpstreamToken()
		if got != "padded-token" {
			t.Errorf("token should be trimmed, got %q", got)
		}
	})
	t.Run("missing token file", func(t *testing.T) {
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{BearerTokenFile: "/nonexistent/token"},
			},
		}})
		got := GetUpstreamToken()
		if got != "" {
			t.Errorf("expected empty for missing file, got %q", got)
		}
	})
	t.Run("nil config returns empty", func(t *testing.T) {
		SetConfig(nil)
		got := GetUpstreamToken()
		if got != "" {
			t.Errorf("expected empty, got %q", got)
		}
	})
}

func TestGetUpstreamCookie(t *testing.T) {
	t.Run("cookie token", func(t *testing.T) {
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{CookieToken: "JSESSIONID=abc123"},
			},
		}})
		got := GetUpstreamCookie()
		if got != "JSESSIONID=abc123" {
			t.Errorf("got %q", got)
		}
	})
	t.Run("cookie token file", func(t *testing.T) {
		tmpFile := filepath.Join(t.TempDir(), "cookie")
		os.WriteFile(tmpFile, []byte("cookie-from-file"), 0644)
		SetConfig(&Config{Auth: mcpconfig.AuthConfig{
			Backend: mcpconfig.BackendAuthConfig{
				Static: mcpconfig.StaticAuthConfig{CookieTokenFile: tmpFile},
			},
		}})
		got := GetUpstreamCookie()
		if got != "cookie-from-file" {
			t.Errorf("got %q", got)
		}
	})
	t.Run("nil config", func(t *testing.T) {
		SetConfig(nil)
		got := GetUpstreamCookie()
		if got != "" {
			t.Errorf("expected empty string, got %q", got)
		}
	})
}

func TestKeyToEnvSegment(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"client_id", "CLIENT_ID"},
		{"clientId", "CLIENT_ID"},
		{"simple", "SIMPLE"},
		{"kebab-case", "KEBAB_CASE"},
		{"enableClientTokenClaimForward", "ENABLE_CLIENT_TOKEN_CLAIM_FORWARD"},
		{"a2a", "A2A"},
		{"downloadDir", "DOWNLOAD_DIR"},
		{"oidc", "OIDC"},
		{"httpTimeout", "HTTP_TIMEOUT"},
		{"bearerToken", "BEARER_TOKEN"},
		{"", ""},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := keyToEnvSegment(tt.input)
			if got != tt.want {
				t.Errorf("keyToEnvSegment(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestNormalizeConfigKey(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"client_id", "clientid"},
		{"CLIENT_ID", "clientid"},
		{"client-id", "clientid"},
		{"ClientId", "clientid"},
		{"upstream-endpoint", "upstreamendpoint"},
		{"UpstreamEndpoint", "upstreamendpoint"},
		{"simple", "simple"},
		{"", ""},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			if got := normalizeConfigKey(tt.input); got != tt.want {
				t.Errorf("normalizeConfigKey(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestMatchConfigKey(t *testing.T) {
	tests := []struct {
		a, b string
		want bool
	}{
		{"client_id", "ClientId", true},
		{"CLIENT-ID", "client_id", true},
		{"upstream_endpoint", "upstreamEndpoint", true},
		{"foo", "foo", true},
		{"different", "other", false},
		{"a", "b", false},
	}
	for _, tt := range tests {
		t.Run(tt.a+"/"+tt.b, func(t *testing.T) {
			if got := matchConfigKey(tt.a, tt.b); got != tt.want {
				t.Errorf("matchConfigKey(%q, %q) = %v, want %v", tt.a, tt.b, got, tt.want)
			}
		})
	}
}

func TestVirtualConfigPath(t *testing.T) {
	got := VirtualConfigPath("test-mcp")
	if got == "" {
		t.Error("VirtualConfigPath returned empty")
	}
	home, _ := os.UserHomeDir()
	want := filepath.Join(home, ".test-mcp", "config.yaml")
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestLogPrintAuth(t *testing.T) {
	t.Run("disabled by default", func(t *testing.T) {
		SetConfig(&Config{})
		if logPrintAuth() {
			t.Error("should be disabled")
		}
	})
	t.Run("enabled", func(t *testing.T) {
		SetConfig(&Config{Runtime: mcpconfig.RuntimeConfig{LogAuthorization: true}})
		if !logPrintAuth() {
			t.Error("should be enabled")
		}
	})
	t.Run("nil config", func(t *testing.T) {
		SetConfig(nil)
		if logPrintAuth() {
			t.Error("nil config should be disabled")
		}
	})
}

func TestResolveUploadDir(t *testing.T) {
	dir, err := resolveUploadDir()
	if err != nil {
		t.Errorf("resolveUploadDir should not error: %v", err)
	}
	if dir == "" {
		t.Error("upload dir should not be empty")
	}
}

func TestResolveDownloadDir(t *testing.T) {
	t.Run("default", func(t *testing.T) {
		SetConfig(&Config{})
		dir, err := resolveDownloadDir()
		if err != nil {
			t.Errorf("resolveDownloadDir should not error: %v", err)
		}
		if dir == "" {
			t.Error("download dir should not be empty")
		}
	})
	t.Run("custom", func(t *testing.T) {
		customDir := filepath.Join(t.TempDir(), "custom-downloads")
		SetConfig(&Config{Runtime: mcpconfig.RuntimeConfig{DownloadDir: customDir}})
		dir, err := resolveDownloadDir()
		if err != nil {
			t.Errorf("resolveDownloadDir should not error: %v", err)
		}
		if dir != customDir {
			t.Errorf("got %q, want %q", dir, customDir)
		}
	})
}
