// Code generated by https://github.com/flowgent-labs/mcpfather
//go:build otel_grpc

package mcputils

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"sync"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

var (
	traceInitOnce sync.Once
	traceReady    bool
	traceProvider *sdktrace.TracerProvider
	appTracer     trace.Tracer
)

// InitTracing initialises the OpenTelemetry tracing pipeline. Must be called once
// at startup before any StartToolSpan. Safe to call when tracing is disabled (no-op).
func InitTracing(cfg OtelConfig) {
	traceInitOnce.Do(func() {
		if !cfg.Enabled {
			return
		}

		endpoint := cfg.Endpoint
		if endpoint == "" {
			return
		}

		timeout := time.Duration(cfg.Timeout) * time.Millisecond
		if timeout <= 0 {
			timeout = 10 * time.Second
		}
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		// Currently only gRPC is supported; http/protobuf can be added later via a
		// separate exporter type when needed.
		exp, err := otlptracegrpc.New(ctx,
			otlptracegrpc.WithEndpoint(endpoint),
			otlptracegrpc.WithInsecure(),
		)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to create OTLP trace exporter: %v\n", err)
			return
		}

		sampler := sdktrace.AlwaysSample()
		if cfg.SampleRate > 0 && cfg.SampleRate < 1.0 {
			sampler = sdktrace.TraceIDRatioBased(cfg.SampleRate)
		}

		traceProvider = sdktrace.NewTracerProvider(
			sdktrace.WithBatcher(exp),
			sdktrace.WithSampler(sampler),
		)
		otel.SetTracerProvider(traceProvider)
		otel.SetTextMapPropagator(propagation.TraceContext{})
		appTracer = traceProvider.Tracer("mcp-tools")
		traceReady = true
	})
}

// StartToolSpan starts a span for an incoming MCP tool call. Returns the
// context (with embedded span) and the span itself for deferred finalization.
// If tracing is not configured the original ctx is returned unchanged.
func StartToolSpan(ctx context.Context, toolName, toolType string) (context.Context, trace.Span) {
	if !traceReady {
		return ctx, trace.SpanFromContext(ctx)
	}
	return appTracer.Start(ctx, "mcp.tool."+toolName,
		trace.WithAttributes(
			attribute.String("tool.name", toolName),
			attribute.String("tool.type", toolType),
		),
	)
}

// InjectTraceContext injects W3C trace context from ctx into the given HTTP
// headers, so upstream services can continue the distributed trace.
func InjectTraceContext(ctx context.Context, headers http.Header) {
	if !traceReady {
		return
	}
	otel.GetTextMapPropagator().Inject(ctx, propagation.HeaderCarrier(headers))
}

// ShutdownTracing flushes and shuts down the trace provider. Safe to call
// even when tracing is not configured (no-op).
func ShutdownTracing(ctx context.Context) error {
	if traceProvider != nil {
		return traceProvider.Shutdown(ctx)
	}
	return nil
}
