// Code generated by https://github.com/flowgent-labs/mcpfather
//go:build !otel_grpc && !otel_http

package mcputils

import (
	"context"
	"net/http"

	"go.opentelemetry.io/otel/trace"
)

// InitTracing is a no-op when built with -tags no_otel.
func InitTracing(cfg OtelConfig) {}

// StartToolSpan is a no-op when built with -tags no_otel.
func StartToolSpan(ctx context.Context, toolName, toolType string) (context.Context, trace.Span) {
	return ctx, trace.SpanFromContext(ctx)
}

// InjectTraceContext is a no-op when built with -tags no_otel.
func InjectTraceContext(ctx context.Context, headers http.Header) {}

// ShutdownTracing is a no-op when built with -tags no_otel.
func ShutdownTracing(ctx context.Context) error { return nil }
